// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	VerifiyCode   string                 `protobuf:"bytes,7,opt,name=verifiyCode,proto3" json:"verifiyCode,omitempty"`
	CreateAt      string                 `protobuf:"bytes,8,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt      string                 `protobuf:"bytes,9,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetVerifiyCode() string {
	if x != nil {
		return x.VerifiyCode
	}
	return ""
}

func (x *User) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *User) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type AuthTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokens) Reset() {
	*x = AuthTokens{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokens) ProtoMessage() {}

func (x *AuthTokens) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokens.ProtoReflect.Descriptor instead.
func (*AuthTokens) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *AuthTokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthTokens) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AuthTokens) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorDetails) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetUserByEmialResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetUserByEmialResponse_User
	//	*GetUserByEmialResponse_Error
	Result        isGetUserByEmialResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmialResponse) Reset() {
	*x = GetUserByEmialResponse{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmialResponse) ProtoMessage() {}

func (x *GetUserByEmialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmialResponse.ProtoReflect.Descriptor instead.
func (*GetUserByEmialResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByEmialResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserByEmialResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserByEmialResponse) GetResult() isGetUserByEmialResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUserByEmialResponse) GetUser() *User {
	if x != nil {
		if x, ok := x.Result.(*GetUserByEmialResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *GetUserByEmialResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetUserByEmialResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetUserByEmialResponse_Result interface {
	isGetUserByEmialResponse_Result()
}

type GetUserByEmialResponse_User struct {
	User *User `protobuf:"bytes,3,opt,name=user,proto3,oneof"`
}

type GetUserByEmialResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetUserByEmialResponse_User) isGetUserByEmialResponse_Result() {}

func (*GetUserByEmialResponse_Error) isGetUserByEmialResponse_Result() {}

type CreateNewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	VerifiyCode   string                 `protobuf:"bytes,7,opt,name=verifiyCode,proto3" json:"verifiyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewUserRequest) Reset() {
	*x = CreateNewUserRequest{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewUserRequest) ProtoMessage() {}

func (x *CreateNewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewUserRequest.ProtoReflect.Descriptor instead.
func (*CreateNewUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNewUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateNewUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateNewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateNewUserRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CreateNewUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateNewUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateNewUserRequest) GetVerifiyCode() string {
	if x != nil {
		return x.VerifiyCode
	}
	return ""
}

type CreateNewUserResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateNewUserResponse_User
	//	*CreateNewUserResponse_Error
	Result        isCreateNewUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewUserResponse) Reset() {
	*x = CreateNewUserResponse{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewUserResponse) ProtoMessage() {}

func (x *CreateNewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewUserResponse.ProtoReflect.Descriptor instead.
func (*CreateNewUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNewUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateNewUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNewUserResponse) GetResult() isCreateNewUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateNewUserResponse) GetUser() *User {
	if x != nil {
		if x, ok := x.Result.(*CreateNewUserResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *CreateNewUserResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*CreateNewUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateNewUserResponse_Result interface {
	isCreateNewUserResponse_Result()
}

type CreateNewUserResponse_User struct {
	User *User `protobuf:"bytes,3,opt,name=user,proto3,oneof"`
}

type CreateNewUserResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CreateNewUserResponse_User) isCreateNewUserResponse_Result() {}

func (*CreateNewUserResponse_Error) isCreateNewUserResponse_Result() {}

type ForgetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordRequest) Reset() {
	*x = ForgetPasswordRequest{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordRequest) ProtoMessage() {}

func (x *ForgetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *ForgetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgetPasswordRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ForgetPasswordResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ForgetPasswordResponse_VerifyCode
	//	*ForgetPasswordResponse_Error
	Result        isForgetPasswordResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordResponse) Reset() {
	*x = ForgetPasswordResponse{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordResponse) ProtoMessage() {}

func (x *ForgetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *ForgetPasswordResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForgetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForgetPasswordResponse) GetResult() isForgetPasswordResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ForgetPasswordResponse) GetVerifyCode() string {
	if x != nil {
		if x, ok := x.Result.(*ForgetPasswordResponse_VerifyCode); ok {
			return x.VerifyCode
		}
	}
	return ""
}

func (x *ForgetPasswordResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*ForgetPasswordResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isForgetPasswordResponse_Result interface {
	isForgetPasswordResponse_Result()
}

type ForgetPasswordResponse_VerifyCode struct {
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode,proto3,oneof"`
}

type ForgetPasswordResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ForgetPasswordResponse_VerifyCode) isForgetPasswordResponse_Result() {}

func (*ForgetPasswordResponse_Error) isForgetPasswordResponse_Result() {}

type VerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,2,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyCodeRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type VerifyCodeResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*VerifyCodeResponse_Response
	//	*VerifyCodeResponse_Error
	Result        isVerifyCodeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeResponse) Reset() {
	*x = VerifyCodeResponse{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeResponse) ProtoMessage() {}

func (x *VerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyCodeResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *VerifyCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyCodeResponse) GetResult() isVerifyCodeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VerifyCodeResponse) GetResponse() string {
	if x != nil {
		if x, ok := x.Result.(*VerifyCodeResponse_Response); ok {
			return x.Response
		}
	}
	return ""
}

func (x *VerifyCodeResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*VerifyCodeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isVerifyCodeResponse_Result interface {
	isVerifyCodeResponse_Result()
}

type VerifyCodeResponse_Response struct {
	Response string `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type VerifyCodeResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*VerifyCodeResponse_Response) isVerifyCodeResponse_Result() {}

func (*VerifyCodeResponse_Error) isVerifyCodeResponse_Result() {}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResetPasswordResponse_Response
	//	*ResetPasswordResponse_Error
	Result        isResetPasswordResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *ResetPasswordResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetPasswordResponse) GetResult() isResetPasswordResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResetPasswordResponse) GetResponse() string {
	if x != nil {
		if x, ok := x.Result.(*ResetPasswordResponse_Response); ok {
			return x.Response
		}
	}
	return ""
}

func (x *ResetPasswordResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*ResetPasswordResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResetPasswordResponse_Result interface {
	isResetPasswordResponse_Result()
}

type ResetPasswordResponse_Response struct {
	Response string `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type ResetPasswordResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ResetPasswordResponse_Response) isResetPasswordResponse_Result() {}

func (*ResetPasswordResponse_Error) isResetPasswordResponse_Result() {}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tokens     *AuthTokens            `protobuf:"bytes,3,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*LoginUserResponse_User
	//	*LoginUserResponse_Error
	Result        isLoginUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *LoginUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LoginUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginUserResponse) GetTokens() *AuthTokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *LoginUserResponse) GetResult() isLoginUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LoginUserResponse) GetUser() *User {
	if x != nil {
		if x, ok := x.Result.(*LoginUserResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *LoginUserResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*LoginUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isLoginUserResponse_Result interface {
	isLoginUserResponse_Result()
}

type LoginUserResponse_User struct {
	User *User `protobuf:"bytes,4,opt,name=user,proto3,oneof"`
}

type LoginUserResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*LoginUserResponse_User) isLoginUserResponse_Result() {}

func (*LoginUserResponse_Error) isLoginUserResponse_Result() {}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateUserResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateUserResponse_User
	//	*UpdateUserResponse_Error
	Result        isUpdateUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserResponse) GetResult() isUpdateUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		if x, ok := x.Result.(*UpdateUserResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *UpdateUserResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UpdateUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateUserResponse_Result interface {
	isUpdateUserResponse_Result()
}

type UpdateUserResponse_User struct {
	User *User `protobuf:"bytes,3,opt,name=user,proto3,oneof"`
}

type UpdateUserResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UpdateUserResponse_User) isUpdateUserResponse_Result() {}

func (*UpdateUserResponse_Error) isUpdateUserResponse_Result() {}

type DeleteUserDatatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDatatRequest) Reset() {
	*x = DeleteUserDatatRequest{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDatatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDatatRequest) ProtoMessage() {}

func (x *DeleteUserDatatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDatatRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserDatatRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserDatatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserDataResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*DeleteUserDataResponse_Response
	//	*DeleteUserDataResponse_Error
	Result        isDeleteUserDataResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDataResponse) Reset() {
	*x = DeleteUserDataResponse{}
	mi := &file_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDataResponse) ProtoMessage() {}

func (x *DeleteUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserDataResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteUserDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteUserDataResponse) GetResult() isDeleteUserDataResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeleteUserDataResponse) GetResponse() string {
	if x != nil {
		if x, ok := x.Result.(*DeleteUserDataResponse_Response); ok {
			return x.Response
		}
	}
	return ""
}

func (x *DeleteUserDataResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*DeleteUserDataResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDeleteUserDataResponse_Result interface {
	isDeleteUserDataResponse_Result()
}

type DeleteUserDataResponse_Response struct {
	Response string `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type DeleteUserDataResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*DeleteUserDataResponse_Response) isDeleteUserDataResponse_Result() {}

func (*DeleteUserDataResponse_Error) isDeleteUserDataResponse_Result() {}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ValidateTokenResponse_Claims
	//	*ValidateTokenResponse_Error
	Result        isValidateTokenResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *ValidateTokenResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ValidateTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateTokenResponse) GetResult() isValidateTokenResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ValidateTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		if x, ok := x.Result.(*ValidateTokenResponse_Claims); ok {
			return x.Claims
		}
	}
	return nil
}

func (x *ValidateTokenResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*ValidateTokenResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isValidateTokenResponse_Result interface {
	isValidateTokenResponse_Result()
}

type ValidateTokenResponse_Claims struct {
	Claims *TokenClaims `protobuf:"bytes,3,opt,name=claims,proto3,oneof"`
}

type ValidateTokenResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ValidateTokenResponse_Claims) isValidateTokenResponse_Result() {}

func (*ValidateTokenResponse_Error) isValidateTokenResponse_Result() {}

type TokenClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TokenClaims) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TokenClaims) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x05users\"\xfa\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12 \n" +
	"\vcountryCode\x18\x04 \x01(\tR\vcountryCode\x12 \n" +
	"\vphoneNumber\x18\x05 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12 \n" +
	"\vverifiyCode\x18\a \x01(\tR\vverifiyCode\x12\x1a\n" +
	"\bcreateAt\x18\b \x01(\tR\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\t \x01(\tR\bupdateAt\"m\n" +
	"\n" +
	"AuthTokens\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1c\n" +
	"\texpiresIn\x18\x02 \x01(\x05R\texpiresIn\x12\x1f\n" +
	"\x04user\x18\x03 \x01(\v2\v.users.UserR\x04user\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"t\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xac\x01\n" +
	"\x16GetUserByEmialResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\v.users.UserH\x00R\x04user\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\xde\x01\n" +
	"\x14CreateNewUserRequest\x12\x1a\n" +
	"\bfullName\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12 \n" +
	"\vcountryCode\x18\x04 \x01(\tR\vcountryCode\x12 \n" +
	"\vphoneNumber\x18\x05 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12 \n" +
	"\vverifiyCode\x18\a \x01(\tR\vverifiyCode\"\xab\x01\n" +
	"\x15CreateNewUserResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\v.users.UserH\x00R\x04user\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"A\n" +
	"\x15ForgetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xab\x01\n" +
	"\x16ForgetPasswordResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\n" +
	"verifyCode\x18\x03 \x01(\tH\x00R\n" +
	"verifyCode\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"I\n" +
	"\x11VerifyCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x02 \x01(\tR\n" +
	"verifyCode\"\xa3\x01\n" +
	"\x12VerifyCodeResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\bresponse\x18\x03 \x01(\tH\x00R\bresponse\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"H\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa6\x01\n" +
	"\x15ResetPasswordResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\bresponse\x18\x03 \x01(\tH\x00R\bresponse\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xd2\x01\n" +
	"\x11LoginUserResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06tokens\x18\x03 \x01(\v2\x11.users.AuthTokensR\x06tokens\x12!\n" +
	"\x04user\x18\x04 \x01(\v2\v.users.UserH\x00R\x04user\x12+\n" +
	"\x05error\x18\x05 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\x9d\x01\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\bfullName\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12 \n" +
	"\vcountryCode\x18\x03 \x01(\tR\vcountryCode\x12 \n" +
	"\vphoneNumber\x18\x04 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\xa8\x01\n" +
	"\x12UpdateUserResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\v.users.UserH\x00R\x04user\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"(\n" +
	"\x16DeleteUserDatatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa7\x01\n" +
	"\x16DeleteUserDataResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\bresponse\x18\x03 \x01(\tH\x00R\bresponse\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xb6\x01\n" +
	"\x15ValidateTokenResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x06claims\x18\x03 \x01(\v2\x12.users.TokenClaimsH\x00R\x06claims\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.users.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"a\n" +
	"\vTokenClaims\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp2\xa9\x05\n" +
	"\vUserService\x12M\n" +
	"\x0eGetUserByEmail\x12\x1c.users.GetUserByEmailRequest\x1a\x1d.users.GetUserByEmialResponse\x12J\n" +
	"\rCreateNewUser\x12\x1b.users.CreateNewUserRequest\x1a\x1c.users.CreateNewUserResponse\x12M\n" +
	"\x0eForgetPassword\x12\x1c.users.ForgetPasswordRequest\x1a\x1d.users.ForgetPasswordResponse\x12A\n" +
	"\n" +
	"VerifyCode\x12\x18.users.VerifyCodeRequest\x1a\x19.users.VerifyCodeResponse\x12J\n" +
	"\rResetPassword\x12\x1b.users.ResetPasswordRequest\x1a\x1c.users.ResetPasswordResponse\x12>\n" +
	"\tLoginUser\x12\x17.users.LoginUserRequest\x1a\x18.users.LoginUserResponse\x12E\n" +
	"\x0eUpdateUserData\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\x12N\n" +
	"\x0eDeleteUserData\x12\x1d.users.DeleteUserDatatRequest\x1a\x1d.users.DeleteUserDataResponse\x12J\n" +
	"\rValidateToken\x12\x1b.users.ValidateTokenRequest\x1a\x1c.users.ValidateTokenResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_user_proto_goTypes = []any{
	(*User)(nil),                   // 0: users.User
	(*AuthTokens)(nil),             // 1: users.AuthTokens
	(*GetUserByEmailRequest)(nil),  // 2: users.GetUserByEmailRequest
	(*ErrorDetails)(nil),           // 3: users.ErrorDetails
	(*GetUserByEmialResponse)(nil), // 4: users.GetUserByEmialResponse
	(*CreateNewUserRequest)(nil),   // 5: users.CreateNewUserRequest
	(*CreateNewUserResponse)(nil),  // 6: users.CreateNewUserResponse
	(*ForgetPasswordRequest)(nil),  // 7: users.ForgetPasswordRequest
	(*ForgetPasswordResponse)(nil), // 8: users.ForgetPasswordResponse
	(*VerifyCodeRequest)(nil),      // 9: users.VerifyCodeRequest
	(*VerifyCodeResponse)(nil),     // 10: users.VerifyCodeResponse
	(*ResetPasswordRequest)(nil),   // 11: users.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),  // 12: users.ResetPasswordResponse
	(*LoginUserRequest)(nil),       // 13: users.LoginUserRequest
	(*LoginUserResponse)(nil),      // 14: users.LoginUserResponse
	(*UpdateUserRequest)(nil),      // 15: users.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 16: users.UpdateUserResponse
	(*DeleteUserDatatRequest)(nil), // 17: users.DeleteUserDatatRequest
	(*DeleteUserDataResponse)(nil), // 18: users.DeleteUserDataResponse
	(*ValidateTokenRequest)(nil),   // 19: users.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),  // 20: users.ValidateTokenResponse
	(*TokenClaims)(nil),            // 21: users.TokenClaims
}
var file_proto_user_proto_depIdxs = []int32{
	0,  // 0: users.AuthTokens.user:type_name -> users.User
	0,  // 1: users.GetUserByEmialResponse.user:type_name -> users.User
	3,  // 2: users.GetUserByEmialResponse.error:type_name -> users.ErrorDetails
	0,  // 3: users.CreateNewUserResponse.user:type_name -> users.User
	3,  // 4: users.CreateNewUserResponse.error:type_name -> users.ErrorDetails
	3,  // 5: users.ForgetPasswordResponse.error:type_name -> users.ErrorDetails
	3,  // 6: users.VerifyCodeResponse.error:type_name -> users.ErrorDetails
	3,  // 7: users.ResetPasswordResponse.error:type_name -> users.ErrorDetails
	1,  // 8: users.LoginUserResponse.tokens:type_name -> users.AuthTokens
	0,  // 9: users.LoginUserResponse.user:type_name -> users.User
	3,  // 10: users.LoginUserResponse.error:type_name -> users.ErrorDetails
	0,  // 11: users.UpdateUserResponse.user:type_name -> users.User
	3,  // 12: users.UpdateUserResponse.error:type_name -> users.ErrorDetails
	3,  // 13: users.DeleteUserDataResponse.error:type_name -> users.ErrorDetails
	21, // 14: users.ValidateTokenResponse.claims:type_name -> users.TokenClaims
	3,  // 15: users.ValidateTokenResponse.error:type_name -> users.ErrorDetails
	2,  // 16: users.UserService.GetUserByEmail:input_type -> users.GetUserByEmailRequest
	5,  // 17: users.UserService.CreateNewUser:input_type -> users.CreateNewUserRequest
	7,  // 18: users.UserService.ForgetPassword:input_type -> users.ForgetPasswordRequest
	9,  // 19: users.UserService.VerifyCode:input_type -> users.VerifyCodeRequest
	11, // 20: users.UserService.ResetPassword:input_type -> users.ResetPasswordRequest
	13, // 21: users.UserService.LoginUser:input_type -> users.LoginUserRequest
	15, // 22: users.UserService.UpdateUserData:input_type -> users.UpdateUserRequest
	17, // 23: users.UserService.DeleteUserData:input_type -> users.DeleteUserDatatRequest
	19, // 24: users.UserService.ValidateToken:input_type -> users.ValidateTokenRequest
	4,  // 25: users.UserService.GetUserByEmail:output_type -> users.GetUserByEmialResponse
	6,  // 26: users.UserService.CreateNewUser:output_type -> users.CreateNewUserResponse
	8,  // 27: users.UserService.ForgetPassword:output_type -> users.ForgetPasswordResponse
	10, // 28: users.UserService.VerifyCode:output_type -> users.VerifyCodeResponse
	12, // 29: users.UserService.ResetPassword:output_type -> users.ResetPasswordResponse
	14, // 30: users.UserService.LoginUser:output_type -> users.LoginUserResponse
	16, // 31: users.UserService.UpdateUserData:output_type -> users.UpdateUserResponse
	18, // 32: users.UserService.DeleteUserData:output_type -> users.DeleteUserDataResponse
	20, // 33: users.UserService.ValidateToken:output_type -> users.ValidateTokenResponse
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	file_proto_user_proto_msgTypes[4].OneofWrappers = []any{
		(*GetUserByEmialResponse_User)(nil),
		(*GetUserByEmialResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[6].OneofWrappers = []any{
		(*CreateNewUserResponse_User)(nil),
		(*CreateNewUserResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[8].OneofWrappers = []any{
		(*ForgetPasswordResponse_VerifyCode)(nil),
		(*ForgetPasswordResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[10].OneofWrappers = []any{
		(*VerifyCodeResponse_Response)(nil),
		(*VerifyCodeResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[12].OneofWrappers = []any{
		(*ResetPasswordResponse_Response)(nil),
		(*ResetPasswordResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[14].OneofWrappers = []any{
		(*LoginUserResponse_User)(nil),
		(*LoginUserResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[16].OneofWrappers = []any{
		(*UpdateUserResponse_User)(nil),
		(*UpdateUserResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[18].OneofWrappers = []any{
		(*DeleteUserDataResponse_Response)(nil),
		(*DeleteUserDataResponse_Error)(nil),
	}
	file_proto_user_proto_msgTypes[20].OneofWrappers = []any{
		(*ValidateTokenResponse_Claims)(nil),
		(*ValidateTokenResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
