// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/user_progress.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,4,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Progress      float32                `protobuf:"fixed32,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Completed     bool                   `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	LastViewed    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_viewed,json=lastViewed,proto3" json:"last_viewed,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_proto_user_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{0}
}

func (x *UserProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UserProgress) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *UserProgress) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UserProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *UserProgress) GetLastViewed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastViewed
	}
	return nil
}

func (x *UserProgress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Achievement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Criteria      map[string]string      `protobuf:"bytes,5,rep,name=criteria,proto3" json:"criteria,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BadgeUrl      string                 `protobuf:"bytes,6,opt,name=badge_url,json=badgeUrl,proto3" json:"badge_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Achievement) Reset() {
	*x = Achievement{}
	mi := &file_proto_user_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Achievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Achievement) ProtoMessage() {}

func (x *Achievement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Achievement.ProtoReflect.Descriptor instead.
func (*Achievement) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{1}
}

func (x *Achievement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Achievement) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Achievement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Achievement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Achievement) GetCriteria() map[string]string {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *Achievement) GetBadgeUrl() string {
	if x != nil {
		return x.BadgeUrl
	}
	return ""
}

func (x *Achievement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserAchievement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AchievementId string                 `protobuf:"bytes,3,opt,name=achievement_id,json=achievementId,proto3" json:"achievement_id,omitempty"`
	Achievement   *Achievement           `protobuf:"bytes,4,opt,name=achievement,proto3" json:"achievement,omitempty"`
	UnlockedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=unlocked_at,json=unlockedAt,proto3" json:"unlocked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAchievement) Reset() {
	*x = UserAchievement{}
	mi := &file_proto_user_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAchievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAchievement) ProtoMessage() {}

func (x *UserAchievement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAchievement.ProtoReflect.Descriptor instead.
func (*UserAchievement) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{2}
}

func (x *UserAchievement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserAchievement) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAchievement) GetAchievementId() string {
	if x != nil {
		return x.AchievementId
	}
	return ""
}

func (x *UserAchievement) GetAchievement() *Achievement {
	if x != nil {
		return x.Achievement
	}
	return nil
}

func (x *UserAchievement) GetUnlockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnlockedAt
	}
	return nil
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_proto_user_progress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorDetails) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_proto_user_progress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProgressRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetUserProgressResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetUserProgressResponse_Progress
	//	*GetUserProgressResponse_Error
	Result        isGetUserProgressResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressResponse) Reset() {
	*x = GetUserProgressResponse{}
	mi := &file_proto_user_progress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressResponse) ProtoMessage() {}

func (x *GetUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressResponse.ProtoReflect.Descriptor instead.
func (*GetUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProgressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserProgressResponse) GetResult() isGetUserProgressResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUserProgressResponse) GetProgress() *UserProgressList {
	if x != nil {
		if x, ok := x.Result.(*GetUserProgressResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *GetUserProgressResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetUserProgressResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetUserProgressResponse_Result interface {
	isGetUserProgressResponse_Result()
}

type GetUserProgressResponse_Progress struct {
	Progress *UserProgressList `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type GetUserProgressResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetUserProgressResponse_Progress) isGetUserProgressResponse_Result() {}

func (*GetUserProgressResponse_Error) isGetUserProgressResponse_Result() {}

type UserProgressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      []*UserProgress        `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgressList) Reset() {
	*x = UserProgressList{}
	mi := &file_proto_user_progress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressList) ProtoMessage() {}

func (x *UserProgressList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressList.ProtoReflect.Descriptor instead.
func (*UserProgressList) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{6}
}

func (x *UserProgressList) GetProgress() []*UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *UserProgressList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Progress      float32                `protobuf:"fixed32,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Completed     bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_user_progress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateProgressRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *UpdateProgressRequest) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UpdateProgressRequest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type UpdateProgressResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateProgressResponse_Progress
	//	*UpdateProgressResponse_Error
	Result        isUpdateProgressResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_proto_user_progress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProgressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProgressResponse) GetResult() isUpdateProgressResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateProgressResponse) GetProgress() *UserProgress {
	if x != nil {
		if x, ok := x.Result.(*UpdateProgressResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *UpdateProgressResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UpdateProgressResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateProgressResponse_Result interface {
	isUpdateProgressResponse_Result()
}

type UpdateProgressResponse_Progress struct {
	Progress *UserProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type UpdateProgressResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UpdateProgressResponse_Progress) isUpdateProgressResponse_Result() {}

func (*UpdateProgressResponse_Error) isUpdateProgressResponse_Result() {}

type GetCompletedTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedTemplatesRequest) Reset() {
	*x = GetCompletedTemplatesRequest{}
	mi := &file_proto_user_progress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedTemplatesRequest) ProtoMessage() {}

func (x *GetCompletedTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetCompletedTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{9}
}

func (x *GetCompletedTemplatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCompletedTemplatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompletedTemplatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCompletedTemplatesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetCompletedTemplatesResponse_Completed
	//	*GetCompletedTemplatesResponse_Error
	Result        isGetCompletedTemplatesResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedTemplatesResponse) Reset() {
	*x = GetCompletedTemplatesResponse{}
	mi := &file_proto_user_progress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedTemplatesResponse) ProtoMessage() {}

func (x *GetCompletedTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetCompletedTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{10}
}

func (x *GetCompletedTemplatesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetCompletedTemplatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCompletedTemplatesResponse) GetResult() isGetCompletedTemplatesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetCompletedTemplatesResponse) GetCompleted() *UserProgressList {
	if x != nil {
		if x, ok := x.Result.(*GetCompletedTemplatesResponse_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *GetCompletedTemplatesResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetCompletedTemplatesResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetCompletedTemplatesResponse_Result interface {
	isGetCompletedTemplatesResponse_Result()
}

type GetCompletedTemplatesResponse_Completed struct {
	Completed *UserProgressList `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

type GetCompletedTemplatesResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetCompletedTemplatesResponse_Completed) isGetCompletedTemplatesResponse_Result() {}

func (*GetCompletedTemplatesResponse_Error) isGetCompletedTemplatesResponse_Result() {}

type GetUserAchievementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAchievementsRequest) Reset() {
	*x = GetUserAchievementsRequest{}
	mi := &file_proto_user_progress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAchievementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAchievementsRequest) ProtoMessage() {}

func (x *GetUserAchievementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAchievementsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAchievementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserAchievementsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAchievementsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetUserAchievementsResponse_Achievements
	//	*GetUserAchievementsResponse_Error
	Result        isGetUserAchievementsResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAchievementsResponse) Reset() {
	*x = GetUserAchievementsResponse{}
	mi := &file_proto_user_progress_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAchievementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAchievementsResponse) ProtoMessage() {}

func (x *GetUserAchievementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAchievementsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAchievementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserAchievementsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserAchievementsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserAchievementsResponse) GetResult() isGetUserAchievementsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUserAchievementsResponse) GetAchievements() *UserAchievementList {
	if x != nil {
		if x, ok := x.Result.(*GetUserAchievementsResponse_Achievements); ok {
			return x.Achievements
		}
	}
	return nil
}

func (x *GetUserAchievementsResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetUserAchievementsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetUserAchievementsResponse_Result interface {
	isGetUserAchievementsResponse_Result()
}

type GetUserAchievementsResponse_Achievements struct {
	Achievements *UserAchievementList `protobuf:"bytes,3,opt,name=achievements,proto3,oneof"`
}

type GetUserAchievementsResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetUserAchievementsResponse_Achievements) isGetUserAchievementsResponse_Result() {}

func (*GetUserAchievementsResponse_Error) isGetUserAchievementsResponse_Result() {}

type UserAchievementList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Achievements  []*UserAchievement     `protobuf:"bytes,1,rep,name=achievements,proto3" json:"achievements,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAchievementList) Reset() {
	*x = UserAchievementList{}
	mi := &file_proto_user_progress_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAchievementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAchievementList) ProtoMessage() {}

func (x *UserAchievementList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAchievementList.ProtoReflect.Descriptor instead.
func (*UserAchievementList) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{13}
}

func (x *UserAchievementList) GetAchievements() []*UserAchievement {
	if x != nil {
		return x.Achievements
	}
	return nil
}

func (x *UserAchievementList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UnlockAchievementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AchievementId string                 `protobuf:"bytes,2,opt,name=achievement_id,json=achievementId,proto3" json:"achievement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockAchievementRequest) Reset() {
	*x = UnlockAchievementRequest{}
	mi := &file_proto_user_progress_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockAchievementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockAchievementRequest) ProtoMessage() {}

func (x *UnlockAchievementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockAchievementRequest.ProtoReflect.Descriptor instead.
func (*UnlockAchievementRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{14}
}

func (x *UnlockAchievementRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnlockAchievementRequest) GetAchievementId() string {
	if x != nil {
		return x.AchievementId
	}
	return ""
}

type UnlockAchievementResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UnlockAchievementResponse_Achievement
	//	*UnlockAchievementResponse_Error
	Result        isUnlockAchievementResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockAchievementResponse) Reset() {
	*x = UnlockAchievementResponse{}
	mi := &file_proto_user_progress_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockAchievementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockAchievementResponse) ProtoMessage() {}

func (x *UnlockAchievementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockAchievementResponse.ProtoReflect.Descriptor instead.
func (*UnlockAchievementResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{15}
}

func (x *UnlockAchievementResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UnlockAchievementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnlockAchievementResponse) GetResult() isUnlockAchievementResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UnlockAchievementResponse) GetAchievement() *UserAchievement {
	if x != nil {
		if x, ok := x.Result.(*UnlockAchievementResponse_Achievement); ok {
			return x.Achievement
		}
	}
	return nil
}

func (x *UnlockAchievementResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UnlockAchievementResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUnlockAchievementResponse_Result interface {
	isUnlockAchievementResponse_Result()
}

type UnlockAchievementResponse_Achievement struct {
	Achievement *UserAchievement `protobuf:"bytes,3,opt,name=achievement,proto3,oneof"`
}

type UnlockAchievementResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UnlockAchievementResponse_Achievement) isUnlockAchievementResponse_Result() {}

func (*UnlockAchievementResponse_Error) isUnlockAchievementResponse_Result() {}

type GetLearningPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLearningPathRequest) Reset() {
	*x = GetLearningPathRequest{}
	mi := &file_proto_user_progress_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearningPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearningPathRequest) ProtoMessage() {}

func (x *GetLearningPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearningPathRequest.ProtoReflect.Descriptor instead.
func (*GetLearningPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{16}
}

func (x *GetLearningPathRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLearningPathResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetLearningPathResponse_Path
	//	*GetLearningPathResponse_Error
	Result        isGetLearningPathResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLearningPathResponse) Reset() {
	*x = GetLearningPathResponse{}
	mi := &file_proto_user_progress_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearningPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearningPathResponse) ProtoMessage() {}

func (x *GetLearningPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearningPathResponse.ProtoReflect.Descriptor instead.
func (*GetLearningPathResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{17}
}

func (x *GetLearningPathResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetLearningPathResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLearningPathResponse) GetResult() isGetLearningPathResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetLearningPathResponse) GetPath() *LearningPath {
	if x != nil {
		if x, ok := x.Result.(*GetLearningPathResponse_Path); ok {
			return x.Path
		}
	}
	return nil
}

func (x *GetLearningPathResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetLearningPathResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetLearningPathResponse_Result interface {
	isGetLearningPathResponse_Result()
}

type GetLearningPathResponse_Path struct {
	Path *LearningPath `protobuf:"bytes,3,opt,name=path,proto3,oneof"`
}

type GetLearningPathResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetLearningPathResponse_Path) isGetLearningPathResponse_Result() {}

func (*GetLearningPathResponse_Error) isGetLearningPathResponse_Result() {}

type LearningPath struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecommendedTemplateIds []string               `protobuf:"bytes,2,rep,name=recommended_template_ids,json=recommendedTemplateIds,proto3" json:"recommended_template_ids,omitempty"`
	OverallProgress        float32                `protobuf:"fixed32,3,opt,name=overall_progress,json=overallProgress,proto3" json:"overall_progress,omitempty"`
	CompletedTemplates     int32                  `protobuf:"varint,4,opt,name=completed_templates,json=completedTemplates,proto3" json:"completed_templates,omitempty"`
	TotalTemplates         int32                  `protobuf:"varint,5,opt,name=total_templates,json=totalTemplates,proto3" json:"total_templates,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LearningPath) Reset() {
	*x = LearningPath{}
	mi := &file_proto_user_progress_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningPath) ProtoMessage() {}

func (x *LearningPath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningPath.ProtoReflect.Descriptor instead.
func (*LearningPath) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_proto_rawDescGZIP(), []int{18}
}

func (x *LearningPath) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LearningPath) GetRecommendedTemplateIds() []string {
	if x != nil {
		return x.RecommendedTemplateIds
	}
	return nil
}

func (x *LearningPath) GetOverallProgress() float32 {
	if x != nil {
		return x.OverallProgress
	}
	return 0
}

func (x *LearningPath) GetCompletedTemplates() int32 {
	if x != nil {
		return x.CompletedTemplates
	}
	return 0
}

func (x *LearningPath) GetTotalTemplates() int32 {
	if x != nil {
		return x.TotalTemplates
	}
	return 0
}

var File_proto_user_progress_proto protoreflect.FileDescriptor

const file_proto_user_progress_proto_rawDesc = "" +
	"\n" +
	"\x19proto/user_progress.proto\x12\ruser_progress\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\fUserProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x04 \x01(\tR\tsectionId\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x02R\bprogress\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\bR\tcompleted\x12;\n" +
	"\vlast_viewed\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastViewed\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc2\x02\n" +
	"\vAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12D\n" +
	"\bcriteria\x18\x05 \x03(\v2(.user_progress.Achievement.CriteriaEntryR\bcriteria\x12\x1b\n" +
	"\tbadge_url\x18\x06 \x01(\tR\bbadgeUrl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rCriteriaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x0fUserAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0eachievement_id\x18\x03 \x01(\tR\rachievementId\x12<\n" +
	"\vachievement\x18\x04 \x01(\v2\x1a.user_progress.AchievementR\vachievement\x12;\n" +
	"\vunlocked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"unlockedAt\"t\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"R\n" +
	"\x16GetUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"\xd2\x01\n" +
	"\x17GetUserProgressResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\bprogress\x18\x03 \x01(\v2\x1f.user_progress.UserProgressListH\x00R\bprogress\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.user_progress.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"l\n" +
	"\x10UserProgressList\x127\n" +
	"\bprogress\x18\x01 \x03(\v2\x1b.user_progress.UserProgressR\bprogress\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xaa\x01\n" +
	"\x15UpdateProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\tR\tsectionId\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x02R\bprogress\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\"\xcd\x01\n" +
	"\x16UpdateProgressResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\bprogress\x18\x03 \x01(\v2\x1b.user_progress.UserProgressH\x00R\bprogress\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.user_progress.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"a\n" +
	"\x1cGetCompletedTemplatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xda\x01\n" +
	"\x1dGetCompletedTemplatesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\tcompleted\x18\x03 \x01(\v2\x1f.user_progress.UserProgressListH\x00R\tcompleted\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.user_progress.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"5\n" +
	"\x1aGetUserAchievementsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe1\x01\n" +
	"\x1bGetUserAchievementsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\fachievements\x18\x03 \x01(\v2\".user_progress.UserAchievementListH\x00R\fachievements\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.user_progress.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"z\n" +
	"\x13UserAchievementList\x12B\n" +
	"\fachievements\x18\x01 \x03(\v2\x1e.user_progress.UserAchievementR\fachievements\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Z\n" +
	"\x18UnlockAchievementRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eachievement_id\x18\x02 \x01(\tR\rachievementId\"\xd9\x01\n" +
	"\x19UnlockAchievementResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\vachievement\x18\x03 \x01(\v2\x1e.user_progress.UserAchievementH\x00R\vachievement\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.user_progress.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"1\n" +
	"\x16GetLearningPathRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc6\x01\n" +
	"\x17GetLearningPathResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04path\x18\x03 \x01(\v2\x1b.user_progress.LearningPathH\x00R\x04path\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.user_progress.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\xe6\x01\n" +
	"\fLearningPath\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\x18recommended_template_ids\x18\x02 \x03(\tR\x16recommendedTemplateIds\x12)\n" +
	"\x10overall_progress\x18\x03 \x01(\x02R\x0foverallProgress\x12/\n" +
	"\x13completed_templates\x18\x04 \x01(\x05R\x12completedTemplates\x12'\n" +
	"\x0ftotal_templates\x18\x05 \x01(\x05R\x0etotalTemplates2\x82\x05\n" +
	"\x13UserProgressService\x12`\n" +
	"\x0fGetUserProgress\x12%.user_progress.GetUserProgressRequest\x1a&.user_progress.GetUserProgressResponse\x12]\n" +
	"\x0eUpdateProgress\x12$.user_progress.UpdateProgressRequest\x1a%.user_progress.UpdateProgressResponse\x12r\n" +
	"\x15GetCompletedTemplates\x12+.user_progress.GetCompletedTemplatesRequest\x1a,.user_progress.GetCompletedTemplatesResponse\x12l\n" +
	"\x13GetUserAchievements\x12).user_progress.GetUserAchievementsRequest\x1a*.user_progress.GetUserAchievementsResponse\x12f\n" +
	"\x11UnlockAchievement\x12'.user_progress.UnlockAchievementRequest\x1a(.user_progress.UnlockAchievementResponse\x12`\n" +
	"\x0fGetLearningPath\x12%.user_progress.GetLearningPathRequest\x1a&.user_progress.GetLearningPathResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_user_progress_proto_rawDescOnce sync.Once
	file_proto_user_progress_proto_rawDescData []byte
)

func file_proto_user_progress_proto_rawDescGZIP() []byte {
	file_proto_user_progress_proto_rawDescOnce.Do(func() {
		file_proto_user_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_progress_proto_rawDesc), len(file_proto_user_progress_proto_rawDesc)))
	})
	return file_proto_user_progress_proto_rawDescData
}

var file_proto_user_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_user_progress_proto_goTypes = []any{
	(*UserProgress)(nil),                  // 0: user_progress.UserProgress
	(*Achievement)(nil),                   // 1: user_progress.Achievement
	(*UserAchievement)(nil),               // 2: user_progress.UserAchievement
	(*ErrorDetails)(nil),                  // 3: user_progress.ErrorDetails
	(*GetUserProgressRequest)(nil),        // 4: user_progress.GetUserProgressRequest
	(*GetUserProgressResponse)(nil),       // 5: user_progress.GetUserProgressResponse
	(*UserProgressList)(nil),              // 6: user_progress.UserProgressList
	(*UpdateProgressRequest)(nil),         // 7: user_progress.UpdateProgressRequest
	(*UpdateProgressResponse)(nil),        // 8: user_progress.UpdateProgressResponse
	(*GetCompletedTemplatesRequest)(nil),  // 9: user_progress.GetCompletedTemplatesRequest
	(*GetCompletedTemplatesResponse)(nil), // 10: user_progress.GetCompletedTemplatesResponse
	(*GetUserAchievementsRequest)(nil),    // 11: user_progress.GetUserAchievementsRequest
	(*GetUserAchievementsResponse)(nil),   // 12: user_progress.GetUserAchievementsResponse
	(*UserAchievementList)(nil),           // 13: user_progress.UserAchievementList
	(*UnlockAchievementRequest)(nil),      // 14: user_progress.UnlockAchievementRequest
	(*UnlockAchievementResponse)(nil),     // 15: user_progress.UnlockAchievementResponse
	(*GetLearningPathRequest)(nil),        // 16: user_progress.GetLearningPathRequest
	(*GetLearningPathResponse)(nil),       // 17: user_progress.GetLearningPathResponse
	(*LearningPath)(nil),                  // 18: user_progress.LearningPath
	nil,                                   // 19: user_progress.Achievement.CriteriaEntry
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
}
var file_proto_user_progress_proto_depIdxs = []int32{
	20, // 0: user_progress.UserProgress.last_viewed:type_name -> google.protobuf.Timestamp
	20, // 1: user_progress.UserProgress.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: user_progress.Achievement.criteria:type_name -> user_progress.Achievement.CriteriaEntry
	20, // 3: user_progress.Achievement.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: user_progress.UserAchievement.achievement:type_name -> user_progress.Achievement
	20, // 5: user_progress.UserAchievement.unlocked_at:type_name -> google.protobuf.Timestamp
	6,  // 6: user_progress.GetUserProgressResponse.progress:type_name -> user_progress.UserProgressList
	3,  // 7: user_progress.GetUserProgressResponse.error:type_name -> user_progress.ErrorDetails
	0,  // 8: user_progress.UserProgressList.progress:type_name -> user_progress.UserProgress
	0,  // 9: user_progress.UpdateProgressResponse.progress:type_name -> user_progress.UserProgress
	3,  // 10: user_progress.UpdateProgressResponse.error:type_name -> user_progress.ErrorDetails
	6,  // 11: user_progress.GetCompletedTemplatesResponse.completed:type_name -> user_progress.UserProgressList
	3,  // 12: user_progress.GetCompletedTemplatesResponse.error:type_name -> user_progress.ErrorDetails
	13, // 13: user_progress.GetUserAchievementsResponse.achievements:type_name -> user_progress.UserAchievementList
	3,  // 14: user_progress.GetUserAchievementsResponse.error:type_name -> user_progress.ErrorDetails
	2,  // 15: user_progress.UserAchievementList.achievements:type_name -> user_progress.UserAchievement
	2,  // 16: user_progress.UnlockAchievementResponse.achievement:type_name -> user_progress.UserAchievement
	3,  // 17: user_progress.UnlockAchievementResponse.error:type_name -> user_progress.ErrorDetails
	18, // 18: user_progress.GetLearningPathResponse.path:type_name -> user_progress.LearningPath
	3,  // 19: user_progress.GetLearningPathResponse.error:type_name -> user_progress.ErrorDetails
	4,  // 20: user_progress.UserProgressService.GetUserProgress:input_type -> user_progress.GetUserProgressRequest
	7,  // 21: user_progress.UserProgressService.UpdateProgress:input_type -> user_progress.UpdateProgressRequest
	9,  // 22: user_progress.UserProgressService.GetCompletedTemplates:input_type -> user_progress.GetCompletedTemplatesRequest
	11, // 23: user_progress.UserProgressService.GetUserAchievements:input_type -> user_progress.GetUserAchievementsRequest
	14, // 24: user_progress.UserProgressService.UnlockAchievement:input_type -> user_progress.UnlockAchievementRequest
	16, // 25: user_progress.UserProgressService.GetLearningPath:input_type -> user_progress.GetLearningPathRequest
	5,  // 26: user_progress.UserProgressService.GetUserProgress:output_type -> user_progress.GetUserProgressResponse
	8,  // 27: user_progress.UserProgressService.UpdateProgress:output_type -> user_progress.UpdateProgressResponse
	10, // 28: user_progress.UserProgressService.GetCompletedTemplates:output_type -> user_progress.GetCompletedTemplatesResponse
	12, // 29: user_progress.UserProgressService.GetUserAchievements:output_type -> user_progress.GetUserAchievementsResponse
	15, // 30: user_progress.UserProgressService.UnlockAchievement:output_type -> user_progress.UnlockAchievementResponse
	17, // 31: user_progress.UserProgressService.GetLearningPath:output_type -> user_progress.GetLearningPathResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_user_progress_proto_init() }
func file_proto_user_progress_proto_init() {
	if File_proto_user_progress_proto != nil {
		return
	}
	file_proto_user_progress_proto_msgTypes[5].OneofWrappers = []any{
		(*GetUserProgressResponse_Progress)(nil),
		(*GetUserProgressResponse_Error)(nil),
	}
	file_proto_user_progress_proto_msgTypes[8].OneofWrappers = []any{
		(*UpdateProgressResponse_Progress)(nil),
		(*UpdateProgressResponse_Error)(nil),
	}
	file_proto_user_progress_proto_msgTypes[10].OneofWrappers = []any{
		(*GetCompletedTemplatesResponse_Completed)(nil),
		(*GetCompletedTemplatesResponse_Error)(nil),
	}
	file_proto_user_progress_proto_msgTypes[12].OneofWrappers = []any{
		(*GetUserAchievementsResponse_Achievements)(nil),
		(*GetUserAchievementsResponse_Error)(nil),
	}
	file_proto_user_progress_proto_msgTypes[15].OneofWrappers = []any{
		(*UnlockAchievementResponse_Achievement)(nil),
		(*UnlockAchievementResponse_Error)(nil),
	}
	file_proto_user_progress_proto_msgTypes[17].OneofWrappers = []any{
		(*GetLearningPathResponse_Path)(nil),
		(*GetLearningPathResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_progress_proto_rawDesc), len(file_proto_user_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_progress_proto_goTypes,
		DependencyIndexes: file_proto_user_progress_proto_depIdxs,
		MessageInfos:      file_proto_user_progress_proto_msgTypes,
	}.Build()
	File_proto_user_progress_proto = out.File
	file_proto_user_progress_proto_goTypes = nil
	file_proto_user_progress_proto_depIdxs = nil
}
