// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/stories.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Story struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Language      string                 `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,11,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	ViewCount     int32                  `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int32                  `protobuf:"varint,13,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,14,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_proto_stories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{0}
}

func (x *Story) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Story) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Story) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Story) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Story) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Story) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Story) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Story) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Story) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Story) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Story) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Story) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Story) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Story) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Story) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Story) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_proto_stories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorDetails) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Create Story
type CreateStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Language      string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	mi := &file_proto_stories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateStoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateStoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateStoryRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateStoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateStoryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateStoryRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateStoryRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CreateStoryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateStoryResponse_Story
	//	*CreateStoryResponse_Error
	Result        isCreateStoryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryResponse) Reset() {
	*x = CreateStoryResponse{}
	mi := &file_proto_stories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryResponse) ProtoMessage() {}

func (x *CreateStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryResponse.ProtoReflect.Descriptor instead.
func (*CreateStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateStoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateStoryResponse) GetResult() isCreateStoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateStoryResponse) GetStory() *Story {
	if x != nil {
		if x, ok := x.Result.(*CreateStoryResponse_Story); ok {
			return x.Story
		}
	}
	return nil
}

func (x *CreateStoryResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*CreateStoryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateStoryResponse_Result interface {
	isCreateStoryResponse_Result()
}

type CreateStoryResponse_Story struct {
	Story *Story `protobuf:"bytes,3,opt,name=story,proto3,oneof"`
}

type CreateStoryResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CreateStoryResponse_Story) isCreateStoryResponse_Result() {}

func (*CreateStoryResponse_Error) isCreateStoryResponse_Result() {}

// Get Story by ID
type GetStoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryByIdRequest) Reset() {
	*x = GetStoryByIdRequest{}
	mi := &file_proto_stories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryByIdRequest) ProtoMessage() {}

func (x *GetStoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetStoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{4}
}

func (x *GetStoryByIdRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type GetStoryByIdResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetStoryByIdResponse_Story
	//	*GetStoryByIdResponse_Error
	Result        isGetStoryByIdResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryByIdResponse) Reset() {
	*x = GetStoryByIdResponse{}
	mi := &file_proto_stories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryByIdResponse) ProtoMessage() {}

func (x *GetStoryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryByIdResponse.ProtoReflect.Descriptor instead.
func (*GetStoryByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoryByIdResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetStoryByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStoryByIdResponse) GetResult() isGetStoryByIdResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetStoryByIdResponse) GetStory() *Story {
	if x != nil {
		if x, ok := x.Result.(*GetStoryByIdResponse_Story); ok {
			return x.Story
		}
	}
	return nil
}

func (x *GetStoryByIdResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetStoryByIdResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetStoryByIdResponse_Result interface {
	isGetStoryByIdResponse_Result()
}

type GetStoryByIdResponse_Story struct {
	Story *Story `protobuf:"bytes,3,opt,name=story,proto3,oneof"`
}

type GetStoryByIdResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetStoryByIdResponse_Story) isGetStoryByIdResponse_Result() {}

func (*GetStoryByIdResponse_Error) isGetStoryByIdResponse_Result() {}

// Get Stories by User
type GetStoriesByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoriesByUserRequest) Reset() {
	*x = GetStoriesByUserRequest{}
	mi := &file_proto_stories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoriesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoriesByUserRequest) ProtoMessage() {}

func (x *GetStoriesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoriesByUserRequest.ProtoReflect.Descriptor instead.
func (*GetStoriesByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{6}
}

func (x *GetStoriesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStoriesByUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetStoriesByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStoriesByUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStoriesByUserResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetStoriesByUserResponse_Stories
	//	*GetStoriesByUserResponse_Error
	Result        isGetStoriesByUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoriesByUserResponse) Reset() {
	*x = GetStoriesByUserResponse{}
	mi := &file_proto_stories_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoriesByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoriesByUserResponse) ProtoMessage() {}

func (x *GetStoriesByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoriesByUserResponse.ProtoReflect.Descriptor instead.
func (*GetStoriesByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{7}
}

func (x *GetStoriesByUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetStoriesByUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStoriesByUserResponse) GetResult() isGetStoriesByUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetStoriesByUserResponse) GetStories() *StoriesList {
	if x != nil {
		if x, ok := x.Result.(*GetStoriesByUserResponse_Stories); ok {
			return x.Stories
		}
	}
	return nil
}

func (x *GetStoriesByUserResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetStoriesByUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetStoriesByUserResponse_Result interface {
	isGetStoriesByUserResponse_Result()
}

type GetStoriesByUserResponse_Stories struct {
	Stories *StoriesList `protobuf:"bytes,3,opt,name=stories,proto3,oneof"`
}

type GetStoriesByUserResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetStoriesByUserResponse_Stories) isGetStoriesByUserResponse_Result() {}

func (*GetStoriesByUserResponse_Error) isGetStoriesByUserResponse_Result() {}

// Get All Stories
type GetAllStoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // Optional filter
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`     // Optional filter
	FeaturedOnly  bool                   `protobuf:"varint,5,opt,name=featured_only,json=featuredOnly,proto3" json:"featured_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStoriesRequest) Reset() {
	*x = GetAllStoriesRequest{}
	mi := &file_proto_stories_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStoriesRequest) ProtoMessage() {}

func (x *GetAllStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStoriesRequest.ProtoReflect.Descriptor instead.
func (*GetAllStoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllStoriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllStoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllStoriesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetAllStoriesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAllStoriesRequest) GetFeaturedOnly() bool {
	if x != nil {
		return x.FeaturedOnly
	}
	return false
}

type GetAllStoriesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetAllStoriesResponse_Stories
	//	*GetAllStoriesResponse_Error
	Result        isGetAllStoriesResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStoriesResponse) Reset() {
	*x = GetAllStoriesResponse{}
	mi := &file_proto_stories_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStoriesResponse) ProtoMessage() {}

func (x *GetAllStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStoriesResponse.ProtoReflect.Descriptor instead.
func (*GetAllStoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllStoriesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllStoriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllStoriesResponse) GetResult() isGetAllStoriesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetAllStoriesResponse) GetStories() *StoriesList {
	if x != nil {
		if x, ok := x.Result.(*GetAllStoriesResponse_Stories); ok {
			return x.Stories
		}
	}
	return nil
}

func (x *GetAllStoriesResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetAllStoriesResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetAllStoriesResponse_Result interface {
	isGetAllStoriesResponse_Result()
}

type GetAllStoriesResponse_Stories struct {
	Stories *StoriesList `protobuf:"bytes,3,opt,name=stories,proto3,oneof"`
}

type GetAllStoriesResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetAllStoriesResponse_Stories) isGetAllStoriesResponse_Result() {}

func (*GetAllStoriesResponse_Error) isGetAllStoriesResponse_Result() {}

type StoriesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       []*Story               `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoriesList) Reset() {
	*x = StoriesList{}
	mi := &file_proto_stories_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoriesList) ProtoMessage() {}

func (x *StoriesList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoriesList.ProtoReflect.Descriptor instead.
func (*StoriesList) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{10}
}

func (x *StoriesList) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *StoriesList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *StoriesList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *StoriesList) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Update Story
type UpdateStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoryRequest) Reset() {
	*x = UpdateStoryRequest{}
	mi := &file_proto_stories_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoryRequest) ProtoMessage() {}

func (x *UpdateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *UpdateStoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateStoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateStoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateStoryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateStoryRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateStoryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateStoryResponse_Story
	//	*UpdateStoryResponse_Error
	Result        isUpdateStoryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoryResponse) Reset() {
	*x = UpdateStoryResponse{}
	mi := &file_proto_stories_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoryResponse) ProtoMessage() {}

func (x *UpdateStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateStoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateStoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateStoryResponse) GetResult() isUpdateStoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateStoryResponse) GetStory() *Story {
	if x != nil {
		if x, ok := x.Result.(*UpdateStoryResponse_Story); ok {
			return x.Story
		}
	}
	return nil
}

func (x *UpdateStoryResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UpdateStoryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateStoryResponse_Result interface {
	isUpdateStoryResponse_Result()
}

type UpdateStoryResponse_Story struct {
	Story *Story `protobuf:"bytes,3,opt,name=story,proto3,oneof"`
}

type UpdateStoryResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UpdateStoryResponse_Story) isUpdateStoryResponse_Result() {}

func (*UpdateStoryResponse_Error) isUpdateStoryResponse_Result() {}

// Delete Story
type DeleteStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoryRequest) Reset() {
	*x = DeleteStoryRequest{}
	mi := &file_proto_stories_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoryRequest) ProtoMessage() {}

func (x *DeleteStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *DeleteStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorDetails          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoryResponse) Reset() {
	*x = DeleteStoryResponse{}
	mi := &file_proto_stories_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoryResponse) ProtoMessage() {}

func (x *DeleteStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteStoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteStoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteStoryResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

// Publish Story
type PublishStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStoryRequest) Reset() {
	*x = PublishStoryRequest{}
	mi := &file_proto_stories_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStoryRequest) ProtoMessage() {}

func (x *PublishStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStoryRequest.ProtoReflect.Descriptor instead.
func (*PublishStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{15}
}

func (x *PublishStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *PublishStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PublishStoryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*PublishStoryResponse_Story
	//	*PublishStoryResponse_Error
	Result        isPublishStoryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStoryResponse) Reset() {
	*x = PublishStoryResponse{}
	mi := &file_proto_stories_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStoryResponse) ProtoMessage() {}

func (x *PublishStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStoryResponse.ProtoReflect.Descriptor instead.
func (*PublishStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{16}
}

func (x *PublishStoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PublishStoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishStoryResponse) GetResult() isPublishStoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PublishStoryResponse) GetStory() *Story {
	if x != nil {
		if x, ok := x.Result.(*PublishStoryResponse_Story); ok {
			return x.Story
		}
	}
	return nil
}

func (x *PublishStoryResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*PublishStoryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isPublishStoryResponse_Result interface {
	isPublishStoryResponse_Result()
}

type PublishStoryResponse_Story struct {
	Story *Story `protobuf:"bytes,3,opt,name=story,proto3,oneof"`
}

type PublishStoryResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*PublishStoryResponse_Story) isPublishStoryResponse_Result() {}

func (*PublishStoryResponse_Error) isPublishStoryResponse_Result() {}

// React to Story
type ReactToStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReactionType  string                 `protobuf:"bytes,3,opt,name=reaction_type,json=reactionType,proto3" json:"reaction_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactToStoryRequest) Reset() {
	*x = ReactToStoryRequest{}
	mi := &file_proto_stories_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactToStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactToStoryRequest) ProtoMessage() {}

func (x *ReactToStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactToStoryRequest.ProtoReflect.Descriptor instead.
func (*ReactToStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{17}
}

func (x *ReactToStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *ReactToStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReactToStoryRequest) GetReactionType() string {
	if x != nil {
		return x.ReactionType
	}
	return ""
}

type ReactToStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorDetails          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactToStoryResponse) Reset() {
	*x = ReactToStoryResponse{}
	mi := &file_proto_stories_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactToStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactToStoryResponse) ProtoMessage() {}

func (x *ReactToStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stories_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactToStoryResponse.ProtoReflect.Descriptor instead.
func (*ReactToStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_stories_proto_rawDescGZIP(), []int{18}
}

func (x *ReactToStoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ReactToStoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReactToStoryResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_stories_proto protoreflect.FileDescriptor

const file_proto_stories_proto_rawDesc = "" +
	"\n" +
	"\x13proto/stories.proto\x12\astories\"\xb9\x03\n" +
	"\x05Story\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1a\n" +
	"\blanguage\x18\n" +
	" \x01(\tR\blanguage\x12\x1f\n" +
	"\vis_featured\x18\v \x01(\bR\n" +
	"isFeatured\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\r \x01(\x05R\tlikeCount\x12!\n" +
	"\fpublished_at\x18\x0e \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"t\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xde\x01\n" +
	"\x12CreateStoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\"\xb1\x01\n" +
	"\x13CreateStoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x05story\x18\x03 \x01(\v2\x0e.stories.StoryH\x00R\x05story\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.stories.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"0\n" +
	"\x13GetStoryByIdRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\"\xb2\x01\n" +
	"\x14GetStoryByIdResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x05story\x18\x03 \x01(\v2\x0e.stories.StoryH\x00R\x05story\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.stories.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"t\n" +
	"\x17GetStoriesByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xc0\x01\n" +
	"\x18GetStoriesByUserResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\astories\x18\x03 \x01(\v2\x14.stories.StoriesListH\x00R\astories\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.stories.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\x99\x01\n" +
	"\x14GetAllStoriesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rfeatured_only\x18\x05 \x01(\bR\ffeaturedOnly\"\xbd\x01\n" +
	"\x15GetAllStoriesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\astories\x18\x03 \x01(\v2\x14.stories.StoriesListH\x00R\astories\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.stories.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\x82\x01\n" +
	"\vStoriesList\x12(\n" +
	"\astories\x18\x01 \x03(\v2\x0e.stories.StoryR\astories\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xac\x01\n" +
	"\x12UpdateStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"\xb1\x01\n" +
	"\x13UpdateStoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x05story\x18\x03 \x01(\v2\x0e.stories.StoryH\x00R\x05story\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.stories.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"H\n" +
	"\x12DeleteStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"}\n" +
	"\x13DeleteStoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.stories.ErrorDetailsR\x05error\"I\n" +
	"\x13PublishStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb2\x01\n" +
	"\x14PublishStoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x05story\x18\x03 \x01(\v2\x0e.stories.StoryH\x00R\x05story\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.stories.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"n\n" +
	"\x13ReactToStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rreaction_type\x18\x03 \x01(\tR\freactionType\"~\n" +
	"\x14ReactToStoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.stories.ErrorDetailsR\x05error2\xfe\x04\n" +
	"\x0eStoriesService\x12H\n" +
	"\vCreateStory\x12\x1b.stories.CreateStoryRequest\x1a\x1c.stories.CreateStoryResponse\x12K\n" +
	"\fGetStoryById\x12\x1c.stories.GetStoryByIdRequest\x1a\x1d.stories.GetStoryByIdResponse\x12W\n" +
	"\x10GetStoriesByUser\x12 .stories.GetStoriesByUserRequest\x1a!.stories.GetStoriesByUserResponse\x12N\n" +
	"\rGetAllStories\x12\x1d.stories.GetAllStoriesRequest\x1a\x1e.stories.GetAllStoriesResponse\x12H\n" +
	"\vUpdateStory\x12\x1b.stories.UpdateStoryRequest\x1a\x1c.stories.UpdateStoryResponse\x12H\n" +
	"\vDeleteStory\x12\x1b.stories.DeleteStoryRequest\x1a\x1c.stories.DeleteStoryResponse\x12K\n" +
	"\fPublishStory\x12\x1c.stories.PublishStoryRequest\x1a\x1d.stories.PublishStoryResponse\x12K\n" +
	"\fReactToStory\x12\x1c.stories.ReactToStoryRequest\x1a\x1d.stories.ReactToStoryResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_stories_proto_rawDescOnce sync.Once
	file_proto_stories_proto_rawDescData []byte
)

func file_proto_stories_proto_rawDescGZIP() []byte {
	file_proto_stories_proto_rawDescOnce.Do(func() {
		file_proto_stories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stories_proto_rawDesc), len(file_proto_stories_proto_rawDesc)))
	})
	return file_proto_stories_proto_rawDescData
}

var file_proto_stories_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_stories_proto_goTypes = []any{
	(*Story)(nil),                    // 0: stories.Story
	(*ErrorDetails)(nil),             // 1: stories.ErrorDetails
	(*CreateStoryRequest)(nil),       // 2: stories.CreateStoryRequest
	(*CreateStoryResponse)(nil),      // 3: stories.CreateStoryResponse
	(*GetStoryByIdRequest)(nil),      // 4: stories.GetStoryByIdRequest
	(*GetStoryByIdResponse)(nil),     // 5: stories.GetStoryByIdResponse
	(*GetStoriesByUserRequest)(nil),  // 6: stories.GetStoriesByUserRequest
	(*GetStoriesByUserResponse)(nil), // 7: stories.GetStoriesByUserResponse
	(*GetAllStoriesRequest)(nil),     // 8: stories.GetAllStoriesRequest
	(*GetAllStoriesResponse)(nil),    // 9: stories.GetAllStoriesResponse
	(*StoriesList)(nil),              // 10: stories.StoriesList
	(*UpdateStoryRequest)(nil),       // 11: stories.UpdateStoryRequest
	(*UpdateStoryResponse)(nil),      // 12: stories.UpdateStoryResponse
	(*DeleteStoryRequest)(nil),       // 13: stories.DeleteStoryRequest
	(*DeleteStoryResponse)(nil),      // 14: stories.DeleteStoryResponse
	(*PublishStoryRequest)(nil),      // 15: stories.PublishStoryRequest
	(*PublishStoryResponse)(nil),     // 16: stories.PublishStoryResponse
	(*ReactToStoryRequest)(nil),      // 17: stories.ReactToStoryRequest
	(*ReactToStoryResponse)(nil),     // 18: stories.ReactToStoryResponse
}
var file_proto_stories_proto_depIdxs = []int32{
	0,  // 0: stories.CreateStoryResponse.story:type_name -> stories.Story
	1,  // 1: stories.CreateStoryResponse.error:type_name -> stories.ErrorDetails
	0,  // 2: stories.GetStoryByIdResponse.story:type_name -> stories.Story
	1,  // 3: stories.GetStoryByIdResponse.error:type_name -> stories.ErrorDetails
	10, // 4: stories.GetStoriesByUserResponse.stories:type_name -> stories.StoriesList
	1,  // 5: stories.GetStoriesByUserResponse.error:type_name -> stories.ErrorDetails
	10, // 6: stories.GetAllStoriesResponse.stories:type_name -> stories.StoriesList
	1,  // 7: stories.GetAllStoriesResponse.error:type_name -> stories.ErrorDetails
	0,  // 8: stories.StoriesList.stories:type_name -> stories.Story
	0,  // 9: stories.UpdateStoryResponse.story:type_name -> stories.Story
	1,  // 10: stories.UpdateStoryResponse.error:type_name -> stories.ErrorDetails
	1,  // 11: stories.DeleteStoryResponse.error:type_name -> stories.ErrorDetails
	0,  // 12: stories.PublishStoryResponse.story:type_name -> stories.Story
	1,  // 13: stories.PublishStoryResponse.error:type_name -> stories.ErrorDetails
	1,  // 14: stories.ReactToStoryResponse.error:type_name -> stories.ErrorDetails
	2,  // 15: stories.StoriesService.CreateStory:input_type -> stories.CreateStoryRequest
	4,  // 16: stories.StoriesService.GetStoryById:input_type -> stories.GetStoryByIdRequest
	6,  // 17: stories.StoriesService.GetStoriesByUser:input_type -> stories.GetStoriesByUserRequest
	8,  // 18: stories.StoriesService.GetAllStories:input_type -> stories.GetAllStoriesRequest
	11, // 19: stories.StoriesService.UpdateStory:input_type -> stories.UpdateStoryRequest
	13, // 20: stories.StoriesService.DeleteStory:input_type -> stories.DeleteStoryRequest
	15, // 21: stories.StoriesService.PublishStory:input_type -> stories.PublishStoryRequest
	17, // 22: stories.StoriesService.ReactToStory:input_type -> stories.ReactToStoryRequest
	3,  // 23: stories.StoriesService.CreateStory:output_type -> stories.CreateStoryResponse
	5,  // 24: stories.StoriesService.GetStoryById:output_type -> stories.GetStoryByIdResponse
	7,  // 25: stories.StoriesService.GetStoriesByUser:output_type -> stories.GetStoriesByUserResponse
	9,  // 26: stories.StoriesService.GetAllStories:output_type -> stories.GetAllStoriesResponse
	12, // 27: stories.StoriesService.UpdateStory:output_type -> stories.UpdateStoryResponse
	14, // 28: stories.StoriesService.DeleteStory:output_type -> stories.DeleteStoryResponse
	16, // 29: stories.StoriesService.PublishStory:output_type -> stories.PublishStoryResponse
	18, // 30: stories.StoriesService.ReactToStory:output_type -> stories.ReactToStoryResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_stories_proto_init() }
func file_proto_stories_proto_init() {
	if File_proto_stories_proto != nil {
		return
	}
	file_proto_stories_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateStoryResponse_Story)(nil),
		(*CreateStoryResponse_Error)(nil),
	}
	file_proto_stories_proto_msgTypes[5].OneofWrappers = []any{
		(*GetStoryByIdResponse_Story)(nil),
		(*GetStoryByIdResponse_Error)(nil),
	}
	file_proto_stories_proto_msgTypes[7].OneofWrappers = []any{
		(*GetStoriesByUserResponse_Stories)(nil),
		(*GetStoriesByUserResponse_Error)(nil),
	}
	file_proto_stories_proto_msgTypes[9].OneofWrappers = []any{
		(*GetAllStoriesResponse_Stories)(nil),
		(*GetAllStoriesResponse_Error)(nil),
	}
	file_proto_stories_proto_msgTypes[12].OneofWrappers = []any{
		(*UpdateStoryResponse_Story)(nil),
		(*UpdateStoryResponse_Error)(nil),
	}
	file_proto_stories_proto_msgTypes[16].OneofWrappers = []any{
		(*PublishStoryResponse_Story)(nil),
		(*PublishStoryResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stories_proto_rawDesc), len(file_proto_stories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stories_proto_goTypes,
		DependencyIndexes: file_proto_stories_proto_depIdxs,
		MessageInfos:      file_proto_stories_proto_msgTypes,
	}.Build()
	File_proto_stories_proto = out.File
	file_proto_stories_proto_goTypes = nil
	file_proto_stories_proto_depIdxs = nil
}
