// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/quiz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionId     string                 `protobuf:"bytes,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrectAnswer string                 `protobuf:"bytes,5,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Explanation   string                 `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Difficulty    string                 `protobuf:"bytes,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_proto_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *Quiz) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Quiz) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Quiz) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *Quiz) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Quiz) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Quiz) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type QuizResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId         string                 `protobuf:"bytes,3,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	SelectedOption string                 `protobuf:"bytes,4,opt,name=selected_option,json=selectedOption,proto3" json:"selected_option,omitempty"`
	IsCorrect      bool                   `protobuf:"varint,5,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	AnsweredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	mi := &file_proto_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *QuizResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizResponse) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *QuizResponse) GetSelectedOption() string {
	if x != nil {
		return x.SelectedOption
	}
	return ""
}

func (x *QuizResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuizResponse) GetAnsweredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnsweredAt
	}
	return nil
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_proto_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorDetails) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetQuizzesBySectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesBySectionRequest) Reset() {
	*x = GetQuizzesBySectionRequest{}
	mi := &file_proto_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesBySectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesBySectionRequest) ProtoMessage() {}

func (x *GetQuizzesBySectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesBySectionRequest.ProtoReflect.Descriptor instead.
func (*GetQuizzesBySectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuizzesBySectionRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

type GetQuizzesBySectionResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetQuizzesBySectionResponse_Quizzes
	//	*GetQuizzesBySectionResponse_Error
	Result        isGetQuizzesBySectionResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesBySectionResponse) Reset() {
	*x = GetQuizzesBySectionResponse{}
	mi := &file_proto_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesBySectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesBySectionResponse) ProtoMessage() {}

func (x *GetQuizzesBySectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesBySectionResponse.ProtoReflect.Descriptor instead.
func (*GetQuizzesBySectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuizzesBySectionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetQuizzesBySectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQuizzesBySectionResponse) GetResult() isGetQuizzesBySectionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetQuizzesBySectionResponse) GetQuizzes() *QuizList {
	if x != nil {
		if x, ok := x.Result.(*GetQuizzesBySectionResponse_Quizzes); ok {
			return x.Quizzes
		}
	}
	return nil
}

func (x *GetQuizzesBySectionResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetQuizzesBySectionResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetQuizzesBySectionResponse_Result interface {
	isGetQuizzesBySectionResponse_Result()
}

type GetQuizzesBySectionResponse_Quizzes struct {
	Quizzes *QuizList `protobuf:"bytes,3,opt,name=quizzes,proto3,oneof"`
}

type GetQuizzesBySectionResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetQuizzesBySectionResponse_Quizzes) isGetQuizzesBySectionResponse_Result() {}

func (*GetQuizzesBySectionResponse_Error) isGetQuizzesBySectionResponse_Result() {}

type QuizList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*Quiz                `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizList) Reset() {
	*x = QuizList{}
	mi := &file_proto_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizList) ProtoMessage() {}

func (x *QuizList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizList.ProtoReflect.Descriptor instead.
func (*QuizList) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *QuizList) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

func (x *QuizList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetQuizByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizByIDRequest) Reset() {
	*x = GetQuizByIDRequest{}
	mi := &file_proto_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizByIDRequest) ProtoMessage() {}

func (x *GetQuizByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizByIDRequest.ProtoReflect.Descriptor instead.
func (*GetQuizByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *GetQuizByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetQuizByIDResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetQuizByIDResponse_Quiz
	//	*GetQuizByIDResponse_Error
	Result        isGetQuizByIDResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizByIDResponse) Reset() {
	*x = GetQuizByIDResponse{}
	mi := &file_proto_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizByIDResponse) ProtoMessage() {}

func (x *GetQuizByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizByIDResponse.ProtoReflect.Descriptor instead.
func (*GetQuizByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuizByIDResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetQuizByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQuizByIDResponse) GetResult() isGetQuizByIDResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetQuizByIDResponse) GetQuiz() *Quiz {
	if x != nil {
		if x, ok := x.Result.(*GetQuizByIDResponse_Quiz); ok {
			return x.Quiz
		}
	}
	return nil
}

func (x *GetQuizByIDResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetQuizByIDResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetQuizByIDResponse_Result interface {
	isGetQuizByIDResponse_Result()
}

type GetQuizByIDResponse_Quiz struct {
	Quiz *Quiz `protobuf:"bytes,3,opt,name=quiz,proto3,oneof"`
}

type GetQuizByIDResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetQuizByIDResponse_Quiz) isGetQuizByIDResponse_Result() {}

func (*GetQuizByIDResponse_Error) isGetQuizByIDResponse_Result() {}

type CreateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	mi := &file_proto_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *CreateQuizRequest) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type CreateQuizResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateQuizResponse_Quiz
	//	*CreateQuizResponse_Error
	Result        isCreateQuizResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizResponse) Reset() {
	*x = CreateQuizResponse{}
	mi := &file_proto_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizResponse) ProtoMessage() {}

func (x *CreateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizResponse.ProtoReflect.Descriptor instead.
func (*CreateQuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *CreateQuizResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateQuizResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateQuizResponse) GetResult() isCreateQuizResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		if x, ok := x.Result.(*CreateQuizResponse_Quiz); ok {
			return x.Quiz
		}
	}
	return nil
}

func (x *CreateQuizResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*CreateQuizResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateQuizResponse_Result interface {
	isCreateQuizResponse_Result()
}

type CreateQuizResponse_Quiz struct {
	Quiz *Quiz `protobuf:"bytes,3,opt,name=quiz,proto3,oneof"`
}

type CreateQuizResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CreateQuizResponse_Quiz) isCreateQuizResponse_Result() {}

func (*CreateQuizResponse_Error) isCreateQuizResponse_Result() {}

type UpdateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quiz          *Quiz                  `protobuf:"bytes,2,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizRequest) Reset() {
	*x = UpdateQuizRequest{}
	mi := &file_proto_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizRequest) ProtoMessage() {}

func (x *UpdateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateQuizRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuizRequest) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type UpdateQuizResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateQuizResponse_Quiz
	//	*UpdateQuizResponse_Error
	Result        isUpdateQuizResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizResponse) Reset() {
	*x = UpdateQuizResponse{}
	mi := &file_proto_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizResponse) ProtoMessage() {}

func (x *UpdateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateQuizResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateQuizResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateQuizResponse) GetResult() isUpdateQuizResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		if x, ok := x.Result.(*UpdateQuizResponse_Quiz); ok {
			return x.Quiz
		}
	}
	return nil
}

func (x *UpdateQuizResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UpdateQuizResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateQuizResponse_Result interface {
	isUpdateQuizResponse_Result()
}

type UpdateQuizResponse_Quiz struct {
	Quiz *Quiz `protobuf:"bytes,3,opt,name=quiz,proto3,oneof"`
}

type UpdateQuizResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UpdateQuizResponse_Quiz) isUpdateQuizResponse_Result() {}

func (*UpdateQuizResponse_Error) isUpdateQuizResponse_Result() {}

type DeleteQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizRequest) Reset() {
	*x = DeleteQuizRequest{}
	mi := &file_proto_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizRequest) ProtoMessage() {}

func (x *DeleteQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteQuizRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteQuizResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*DeleteQuizResponse_Success
	//	*DeleteQuizResponse_Error
	Result        isDeleteQuizResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizResponse) Reset() {
	*x = DeleteQuizResponse{}
	mi := &file_proto_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizResponse) ProtoMessage() {}

func (x *DeleteQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteQuizResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteQuizResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteQuizResponse) GetResult() isDeleteQuizResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeleteQuizResponse) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Result.(*DeleteQuizResponse_Success); ok {
			return x.Success
		}
	}
	return false
}

func (x *DeleteQuizResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*DeleteQuizResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDeleteQuizResponse_Result interface {
	isDeleteQuizResponse_Result()
}

type DeleteQuizResponse_Success struct {
	Success bool `protobuf:"varint,3,opt,name=success,proto3,oneof"`
}

type DeleteQuizResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*DeleteQuizResponse_Success) isDeleteQuizResponse_Result() {}

func (*DeleteQuizResponse_Error) isDeleteQuizResponse_Result() {}

type SubmitQuizAnswerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId         string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	SelectedOption string                 `protobuf:"bytes,3,opt,name=selected_option,json=selectedOption,proto3" json:"selected_option,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitQuizAnswerRequest) Reset() {
	*x = SubmitQuizAnswerRequest{}
	mi := &file_proto_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQuizAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizAnswerRequest) ProtoMessage() {}

func (x *SubmitQuizAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitQuizAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitQuizAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitQuizAnswerRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *SubmitQuizAnswerRequest) GetSelectedOption() string {
	if x != nil {
		return x.SelectedOption
	}
	return ""
}

type SubmitQuizAnswerResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*SubmitQuizAnswerResponse_Response
	//	*SubmitQuizAnswerResponse_Error
	Result        isSubmitQuizAnswerResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitQuizAnswerResponse) Reset() {
	*x = SubmitQuizAnswerResponse{}
	mi := &file_proto_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQuizAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizAnswerResponse) ProtoMessage() {}

func (x *SubmitQuizAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitQuizAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitQuizAnswerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SubmitQuizAnswerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitQuizAnswerResponse) GetResult() isSubmitQuizAnswerResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SubmitQuizAnswerResponse) GetResponse() *QuizResponse {
	if x != nil {
		if x, ok := x.Result.(*SubmitQuizAnswerResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *SubmitQuizAnswerResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*SubmitQuizAnswerResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSubmitQuizAnswerResponse_Result interface {
	isSubmitQuizAnswerResponse_Result()
}

type SubmitQuizAnswerResponse_Response struct {
	Response *QuizResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type SubmitQuizAnswerResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SubmitQuizAnswerResponse_Response) isSubmitQuizAnswerResponse_Result() {}

func (*SubmitQuizAnswerResponse_Error) isSubmitQuizAnswerResponse_Result() {}

type GetUserQuizHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserQuizHistoryRequest) Reset() {
	*x = GetUserQuizHistoryRequest{}
	mi := &file_proto_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserQuizHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserQuizHistoryRequest) ProtoMessage() {}

func (x *GetUserQuizHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserQuizHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetUserQuizHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserQuizHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserQuizHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserQuizHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserQuizHistoryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetUserQuizHistoryResponse_Responses
	//	*GetUserQuizHistoryResponse_Error
	Result        isGetUserQuizHistoryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserQuizHistoryResponse) Reset() {
	*x = GetUserQuizHistoryResponse{}
	mi := &file_proto_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserQuizHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserQuizHistoryResponse) ProtoMessage() {}

func (x *GetUserQuizHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserQuizHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserQuizHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserQuizHistoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserQuizHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserQuizHistoryResponse) GetResult() isGetUserQuizHistoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUserQuizHistoryResponse) GetResponses() *QuizResponseList {
	if x != nil {
		if x, ok := x.Result.(*GetUserQuizHistoryResponse_Responses); ok {
			return x.Responses
		}
	}
	return nil
}

func (x *GetUserQuizHistoryResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetUserQuizHistoryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetUserQuizHistoryResponse_Result interface {
	isGetUserQuizHistoryResponse_Result()
}

type GetUserQuizHistoryResponse_Responses struct {
	Responses *QuizResponseList `protobuf:"bytes,3,opt,name=responses,proto3,oneof"`
}

type GetUserQuizHistoryResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetUserQuizHistoryResponse_Responses) isGetUserQuizHistoryResponse_Result() {}

func (*GetUserQuizHistoryResponse_Error) isGetUserQuizHistoryResponse_Result() {}

type QuizResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*QuizResponse        `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResponseList) Reset() {
	*x = QuizResponseList{}
	mi := &file_proto_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponseList) ProtoMessage() {}

func (x *QuizResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponseList.ProtoReflect.Descriptor instead.
func (*QuizResponseList) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *QuizResponseList) GetResponses() []*QuizResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *QuizResponseList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QuizResponseList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QuizResponseList) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetQuizStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizStatisticsRequest) Reset() {
	*x = GetQuizStatisticsRequest{}
	mi := &file_proto_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizStatisticsRequest) ProtoMessage() {}

func (x *GetQuizStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetQuizStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{19}
}

func (x *GetQuizStatisticsRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type GetQuizStatisticsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetQuizStatisticsResponse_Statistics
	//	*GetQuizStatisticsResponse_Error
	Result        isGetQuizStatisticsResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizStatisticsResponse) Reset() {
	*x = GetQuizStatisticsResponse{}
	mi := &file_proto_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizStatisticsResponse) ProtoMessage() {}

func (x *GetQuizStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetQuizStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *GetQuizStatisticsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetQuizStatisticsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQuizStatisticsResponse) GetResult() isGetQuizStatisticsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetQuizStatisticsResponse) GetStatistics() *QuizStatistics {
	if x != nil {
		if x, ok := x.Result.(*GetQuizStatisticsResponse_Statistics); ok {
			return x.Statistics
		}
	}
	return nil
}

func (x *GetQuizStatisticsResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetQuizStatisticsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetQuizStatisticsResponse_Result interface {
	isGetQuizStatisticsResponse_Result()
}

type GetQuizStatisticsResponse_Statistics struct {
	Statistics *QuizStatistics `protobuf:"bytes,3,opt,name=statistics,proto3,oneof"`
}

type GetQuizStatisticsResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetQuizStatisticsResponse_Statistics) isGetQuizStatisticsResponse_Result() {}

func (*GetQuizStatisticsResponse_Error) isGetQuizStatisticsResponse_Result() {}

type QuizStatistics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuizId          string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	TotalAttempts   int32                  `protobuf:"varint,2,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	CorrectAttempts int32                  `protobuf:"varint,3,opt,name=correct_attempts,json=correctAttempts,proto3" json:"correct_attempts,omitempty"`
	SuccessRate     float32                `protobuf:"fixed32,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageTime     float32                `protobuf:"fixed32,5,opt,name=average_time,json=averageTime,proto3" json:"average_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuizStatistics) Reset() {
	*x = QuizStatistics{}
	mi := &file_proto_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizStatistics) ProtoMessage() {}

func (x *QuizStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizStatistics.ProtoReflect.Descriptor instead.
func (*QuizStatistics) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *QuizStatistics) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *QuizStatistics) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *QuizStatistics) GetCorrectAttempts() int32 {
	if x != nil {
		return x.CorrectAttempts
	}
	return 0
}

func (x *QuizStatistics) GetSuccessRate() float32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *QuizStatistics) GetAverageTime() float32 {
	if x != nil {
		return x.AverageTime
	}
	return 0
}

var File_proto_quiz_proto protoreflect.FileDescriptor

const file_proto_quiz_proto_rawDesc = "" +
	"\n" +
	"\x10proto/quiz.proto\x12\x04quiz\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x02\n" +
	"\x04Quiz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\tR\tsectionId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x121\n" +
	"\aoptions\x18\x04 \x03(\v2\x17.quiz.Quiz.OptionsEntryR\aoptions\x12%\n" +
	"\x0ecorrect_answer\x18\x05 \x01(\tR\rcorrectAnswer\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\tR\n" +
	"difficulty\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\fQuizResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x03 \x01(\tR\x06quizId\x12'\n" +
	"\x0fselected_option\x18\x04 \x01(\tR\x0eselectedOption\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x05 \x01(\bR\tisCorrect\x12;\n" +
	"\vanswered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"answeredAt\"t\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\";\n" +
	"\x1aGetQuizzesBySectionRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\"\xba\x01\n" +
	"\x1bGetQuizzesBySectionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\aquizzes\x18\x03 \x01(\v2\x0e.quiz.QuizListH\x00R\aquizzes\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"Q\n" +
	"\bQuizList\x12$\n" +
	"\aquizzes\x18\x01 \x03(\v2\n" +
	".quiz.QuizR\aquizzes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"$\n" +
	"\x12GetQuizByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa8\x01\n" +
	"\x13GetQuizByIDResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04quiz\x18\x03 \x01(\v2\n" +
	".quiz.QuizH\x00R\x04quiz\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"3\n" +
	"\x11CreateQuizRequest\x12\x1e\n" +
	"\x04quiz\x18\x01 \x01(\v2\n" +
	".quiz.QuizR\x04quiz\"\xa7\x01\n" +
	"\x12CreateQuizResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04quiz\x18\x03 \x01(\v2\n" +
	".quiz.QuizH\x00R\x04quiz\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"C\n" +
	"\x11UpdateQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\x04quiz\x18\x02 \x01(\v2\n" +
	".quiz.QuizR\x04quiz\"\xa7\x01\n" +
	"\x12UpdateQuizResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04quiz\x18\x03 \x01(\v2\n" +
	".quiz.QuizH\x00R\x04quiz\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"#\n" +
	"\x11DeleteQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x01\n" +
	"\x12DeleteQuizResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\asuccess\x18\x03 \x01(\bH\x00R\asuccess\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"t\n" +
	"\x17SubmitQuizAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12'\n" +
	"\x0fselected_option\x18\x03 \x01(\tR\x0eselectedOption\"\xbd\x01\n" +
	"\x18SubmitQuizAnswerResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bresponse\x18\x03 \x01(\v2\x12.quiz.QuizResponseH\x00R\bresponse\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"^\n" +
	"\x19GetUserQuizHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc5\x01\n" +
	"\x1aGetUserQuizHistoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\tresponses\x18\x03 \x01(\v2\x16.quiz.QuizResponseListH\x00R\tresponses\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\x8f\x01\n" +
	"\x10QuizResponseList\x120\n" +
	"\tresponses\x18\x01 \x03(\v2\x12.quiz.QuizResponseR\tresponses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"3\n" +
	"\x18GetQuizStatisticsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\"\xc4\x01\n" +
	"\x19GetQuizStatisticsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\n" +
	"statistics\x18\x03 \x01(\v2\x14.quiz.QuizStatisticsH\x00R\n" +
	"statistics\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.quiz.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\xc1\x01\n" +
	"\x0eQuizStatistics\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12%\n" +
	"\x0etotal_attempts\x18\x02 \x01(\x05R\rtotalAttempts\x12)\n" +
	"\x10correct_attempts\x18\x03 \x01(\x05R\x0fcorrectAttempts\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x02R\vsuccessRate\x12!\n" +
	"\faverage_time\x18\x05 \x01(\x02R\vaverageTime2\xf2\x04\n" +
	"\vQuizService\x12Z\n" +
	"\x13GetQuizzesBySection\x12 .quiz.GetQuizzesBySectionRequest\x1a!.quiz.GetQuizzesBySectionResponse\x12B\n" +
	"\vGetQuizByID\x12\x18.quiz.GetQuizByIDRequest\x1a\x19.quiz.GetQuizByIDResponse\x12?\n" +
	"\n" +
	"CreateQuiz\x12\x17.quiz.CreateQuizRequest\x1a\x18.quiz.CreateQuizResponse\x12?\n" +
	"\n" +
	"UpdateQuiz\x12\x17.quiz.UpdateQuizRequest\x1a\x18.quiz.UpdateQuizResponse\x12?\n" +
	"\n" +
	"DeleteQuiz\x12\x17.quiz.DeleteQuizRequest\x1a\x18.quiz.DeleteQuizResponse\x12Q\n" +
	"\x10SubmitQuizAnswer\x12\x1d.quiz.SubmitQuizAnswerRequest\x1a\x1e.quiz.SubmitQuizAnswerResponse\x12W\n" +
	"\x12GetUserQuizHistory\x12\x1f.quiz.GetUserQuizHistoryRequest\x1a .quiz.GetUserQuizHistoryResponse\x12T\n" +
	"\x11GetQuizStatistics\x12\x1e.quiz.GetQuizStatisticsRequest\x1a\x1f.quiz.GetQuizStatisticsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_quiz_proto_rawDescOnce sync.Once
	file_proto_quiz_proto_rawDescData []byte
)

func file_proto_quiz_proto_rawDescGZIP() []byte {
	file_proto_quiz_proto_rawDescOnce.Do(func() {
		file_proto_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)))
	})
	return file_proto_quiz_proto_rawDescData
}

var file_proto_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_quiz_proto_goTypes = []any{
	(*Quiz)(nil),                        // 0: quiz.Quiz
	(*QuizResponse)(nil),                // 1: quiz.QuizResponse
	(*ErrorDetails)(nil),                // 2: quiz.ErrorDetails
	(*GetQuizzesBySectionRequest)(nil),  // 3: quiz.GetQuizzesBySectionRequest
	(*GetQuizzesBySectionResponse)(nil), // 4: quiz.GetQuizzesBySectionResponse
	(*QuizList)(nil),                    // 5: quiz.QuizList
	(*GetQuizByIDRequest)(nil),          // 6: quiz.GetQuizByIDRequest
	(*GetQuizByIDResponse)(nil),         // 7: quiz.GetQuizByIDResponse
	(*CreateQuizRequest)(nil),           // 8: quiz.CreateQuizRequest
	(*CreateQuizResponse)(nil),          // 9: quiz.CreateQuizResponse
	(*UpdateQuizRequest)(nil),           // 10: quiz.UpdateQuizRequest
	(*UpdateQuizResponse)(nil),          // 11: quiz.UpdateQuizResponse
	(*DeleteQuizRequest)(nil),           // 12: quiz.DeleteQuizRequest
	(*DeleteQuizResponse)(nil),          // 13: quiz.DeleteQuizResponse
	(*SubmitQuizAnswerRequest)(nil),     // 14: quiz.SubmitQuizAnswerRequest
	(*SubmitQuizAnswerResponse)(nil),    // 15: quiz.SubmitQuizAnswerResponse
	(*GetUserQuizHistoryRequest)(nil),   // 16: quiz.GetUserQuizHistoryRequest
	(*GetUserQuizHistoryResponse)(nil),  // 17: quiz.GetUserQuizHistoryResponse
	(*QuizResponseList)(nil),            // 18: quiz.QuizResponseList
	(*GetQuizStatisticsRequest)(nil),    // 19: quiz.GetQuizStatisticsRequest
	(*GetQuizStatisticsResponse)(nil),   // 20: quiz.GetQuizStatisticsResponse
	(*QuizStatistics)(nil),              // 21: quiz.QuizStatistics
	nil,                                 // 22: quiz.Quiz.OptionsEntry
	(*timestamppb.Timestamp)(nil),       // 23: google.protobuf.Timestamp
}
var file_proto_quiz_proto_depIdxs = []int32{
	22, // 0: quiz.Quiz.options:type_name -> quiz.Quiz.OptionsEntry
	23, // 1: quiz.Quiz.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: quiz.QuizResponse.answered_at:type_name -> google.protobuf.Timestamp
	5,  // 3: quiz.GetQuizzesBySectionResponse.quizzes:type_name -> quiz.QuizList
	2,  // 4: quiz.GetQuizzesBySectionResponse.error:type_name -> quiz.ErrorDetails
	0,  // 5: quiz.QuizList.quizzes:type_name -> quiz.Quiz
	0,  // 6: quiz.GetQuizByIDResponse.quiz:type_name -> quiz.Quiz
	2,  // 7: quiz.GetQuizByIDResponse.error:type_name -> quiz.ErrorDetails
	0,  // 8: quiz.CreateQuizRequest.quiz:type_name -> quiz.Quiz
	0,  // 9: quiz.CreateQuizResponse.quiz:type_name -> quiz.Quiz
	2,  // 10: quiz.CreateQuizResponse.error:type_name -> quiz.ErrorDetails
	0,  // 11: quiz.UpdateQuizRequest.quiz:type_name -> quiz.Quiz
	0,  // 12: quiz.UpdateQuizResponse.quiz:type_name -> quiz.Quiz
	2,  // 13: quiz.UpdateQuizResponse.error:type_name -> quiz.ErrorDetails
	2,  // 14: quiz.DeleteQuizResponse.error:type_name -> quiz.ErrorDetails
	1,  // 15: quiz.SubmitQuizAnswerResponse.response:type_name -> quiz.QuizResponse
	2,  // 16: quiz.SubmitQuizAnswerResponse.error:type_name -> quiz.ErrorDetails
	18, // 17: quiz.GetUserQuizHistoryResponse.responses:type_name -> quiz.QuizResponseList
	2,  // 18: quiz.GetUserQuizHistoryResponse.error:type_name -> quiz.ErrorDetails
	1,  // 19: quiz.QuizResponseList.responses:type_name -> quiz.QuizResponse
	21, // 20: quiz.GetQuizStatisticsResponse.statistics:type_name -> quiz.QuizStatistics
	2,  // 21: quiz.GetQuizStatisticsResponse.error:type_name -> quiz.ErrorDetails
	3,  // 22: quiz.QuizService.GetQuizzesBySection:input_type -> quiz.GetQuizzesBySectionRequest
	6,  // 23: quiz.QuizService.GetQuizByID:input_type -> quiz.GetQuizByIDRequest
	8,  // 24: quiz.QuizService.CreateQuiz:input_type -> quiz.CreateQuizRequest
	10, // 25: quiz.QuizService.UpdateQuiz:input_type -> quiz.UpdateQuizRequest
	12, // 26: quiz.QuizService.DeleteQuiz:input_type -> quiz.DeleteQuizRequest
	14, // 27: quiz.QuizService.SubmitQuizAnswer:input_type -> quiz.SubmitQuizAnswerRequest
	16, // 28: quiz.QuizService.GetUserQuizHistory:input_type -> quiz.GetUserQuizHistoryRequest
	19, // 29: quiz.QuizService.GetQuizStatistics:input_type -> quiz.GetQuizStatisticsRequest
	4,  // 30: quiz.QuizService.GetQuizzesBySection:output_type -> quiz.GetQuizzesBySectionResponse
	7,  // 31: quiz.QuizService.GetQuizByID:output_type -> quiz.GetQuizByIDResponse
	9,  // 32: quiz.QuizService.CreateQuiz:output_type -> quiz.CreateQuizResponse
	11, // 33: quiz.QuizService.UpdateQuiz:output_type -> quiz.UpdateQuizResponse
	13, // 34: quiz.QuizService.DeleteQuiz:output_type -> quiz.DeleteQuizResponse
	15, // 35: quiz.QuizService.SubmitQuizAnswer:output_type -> quiz.SubmitQuizAnswerResponse
	17, // 36: quiz.QuizService.GetUserQuizHistory:output_type -> quiz.GetUserQuizHistoryResponse
	20, // 37: quiz.QuizService.GetQuizStatistics:output_type -> quiz.GetQuizStatisticsResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_quiz_proto_init() }
func file_proto_quiz_proto_init() {
	if File_proto_quiz_proto != nil {
		return
	}
	file_proto_quiz_proto_msgTypes[4].OneofWrappers = []any{
		(*GetQuizzesBySectionResponse_Quizzes)(nil),
		(*GetQuizzesBySectionResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[7].OneofWrappers = []any{
		(*GetQuizByIDResponse_Quiz)(nil),
		(*GetQuizByIDResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[9].OneofWrappers = []any{
		(*CreateQuizResponse_Quiz)(nil),
		(*CreateQuizResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[11].OneofWrappers = []any{
		(*UpdateQuizResponse_Quiz)(nil),
		(*UpdateQuizResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[13].OneofWrappers = []any{
		(*DeleteQuizResponse_Success)(nil),
		(*DeleteQuizResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[15].OneofWrappers = []any{
		(*SubmitQuizAnswerResponse_Response)(nil),
		(*SubmitQuizAnswerResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[17].OneofWrappers = []any{
		(*GetUserQuizHistoryResponse_Responses)(nil),
		(*GetUserQuizHistoryResponse_Error)(nil),
	}
	file_proto_quiz_proto_msgTypes[20].OneofWrappers = []any{
		(*GetQuizStatisticsResponse_Statistics)(nil),
		(*GetQuizStatisticsResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quiz_proto_goTypes,
		DependencyIndexes: file_proto_quiz_proto_depIdxs,
		MessageInfos:      file_proto_quiz_proto_msgTypes,
	}.Build()
	File_proto_quiz_proto = out.File
	file_proto_quiz_proto_goTypes = nil
	file_proto_quiz_proto_depIdxs = nil
}
