// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/card.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CardNumber     string                 `protobuf:"bytes,3,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	CardHolderName string                 `protobuf:"bytes,4,opt,name=cardHolderName,proto3" json:"cardHolderName,omitempty"`
	ExpirationDate string                 `protobuf:"bytes,5,opt,name=expirationDate,proto3" json:"expirationDate,omitempty"`
	Cvv            string                 `protobuf:"bytes,6,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CardType       string                 `protobuf:"bytes,8,opt,name=cardType,proto3" json:"cardType,omitempty"`
	Balance        string                 `protobuf:"bytes,9,opt,name=balance,proto3" json:"balance,omitempty"`
	CreateAt       string                 `protobuf:"bytes,10,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt       string                 `protobuf:"bytes,11,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Card) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Card) GetCardHolderName() string {
	if x != nil {
		return x.CardHolderName
	}
	return ""
}

func (x *Card) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *Card) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *Card) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Card) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Card) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Card) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Card) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_proto_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorDetails) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetCardByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardByIDRequest) Reset() {
	*x = GetCardByIDRequest{}
	mi := &file_proto_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardByIDRequest) ProtoMessage() {}

func (x *GetCardByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCardByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCardByIDResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetCardByIDResponse_Card
	//	*GetCardByIDResponse_Error
	Result        isGetCardByIDResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardByIDResponse) Reset() {
	*x = GetCardByIDResponse{}
	mi := &file_proto_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardByIDResponse) ProtoMessage() {}

func (x *GetCardByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCardByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardByIDResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetCardByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCardByIDResponse) GetResult() isGetCardByIDResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetCardByIDResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*GetCardByIDResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *GetCardByIDResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetCardByIDResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetCardByIDResponse_Result interface {
	isGetCardByIDResponse_Result()
}

type GetCardByIDResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type GetCardByIDResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetCardByIDResponse_Card) isGetCardByIDResponse_Result() {}

func (*GetCardByIDResponse_Error) isGetCardByIDResponse_Result() {}

type CreateNewCardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CardNumber     string                 `protobuf:"bytes,2,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	CardHolderName string                 `protobuf:"bytes,3,opt,name=cardHolderName,proto3" json:"cardHolderName,omitempty"`
	ExpirationDate string                 `protobuf:"bytes,4,opt,name=expirationDate,proto3" json:"expirationDate,omitempty"`
	Cvv            string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CardType       string                 `protobuf:"bytes,7,opt,name=cardType,proto3" json:"cardType,omitempty"`
	Balance        string                 `protobuf:"bytes,8,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNewCardRequest) Reset() {
	*x = CreateNewCardRequest{}
	mi := &file_proto_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewCardRequest) ProtoMessage() {}

func (x *CreateNewCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewCardRequest.ProtoReflect.Descriptor instead.
func (*CreateNewCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{4}
}

func (x *CreateNewCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNewCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateNewCardRequest) GetCardHolderName() string {
	if x != nil {
		return x.CardHolderName
	}
	return ""
}

func (x *CreateNewCardRequest) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *CreateNewCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CreateNewCardRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateNewCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateNewCardRequest) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type CreateNewCardResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateNewCardResponse_Card
	//	*CreateNewCardResponse_Error
	Result        isCreateNewCardResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewCardResponse) Reset() {
	*x = CreateNewCardResponse{}
	mi := &file_proto_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewCardResponse) ProtoMessage() {}

func (x *CreateNewCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewCardResponse.ProtoReflect.Descriptor instead.
func (*CreateNewCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNewCardResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateNewCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNewCardResponse) GetResult() isCreateNewCardResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateNewCardResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*CreateNewCardResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *CreateNewCardResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*CreateNewCardResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateNewCardResponse_Result interface {
	isCreateNewCardResponse_Result()
}

type CreateNewCardResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type CreateNewCardResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CreateNewCardResponse_Card) isCreateNewCardResponse_Result() {}

func (*CreateNewCardResponse_Error) isCreateNewCardResponse_Result() {}

type UpdateCardDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber     string                 `protobuf:"bytes,2,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	CardHolderName string                 `protobuf:"bytes,3,opt,name=cardHolderName,proto3" json:"cardHolderName,omitempty"`
	ExpirationDate string                 `protobuf:"bytes,4,opt,name=expirationDate,proto3" json:"expirationDate,omitempty"`
	Cvv            string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CardType       string                 `protobuf:"bytes,7,opt,name=cardType,proto3" json:"cardType,omitempty"`
	Balance        string                 `protobuf:"bytes,8,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCardDataRequest) Reset() {
	*x = UpdateCardDataRequest{}
	mi := &file_proto_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardDataRequest) ProtoMessage() {}

func (x *UpdateCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCardDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCardDataRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateCardDataRequest) GetCardHolderName() string {
	if x != nil {
		return x.CardHolderName
	}
	return ""
}

func (x *UpdateCardDataRequest) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *UpdateCardDataRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *UpdateCardDataRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCardDataRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *UpdateCardDataRequest) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type UpdateCardDataResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateCardDataResponse_Card
	//	*UpdateCardDataResponse_Error
	Result        isUpdateCardDataResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardDataResponse) Reset() {
	*x = UpdateCardDataResponse{}
	mi := &file_proto_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardDataResponse) ProtoMessage() {}

func (x *UpdateCardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCardDataResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateCardDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCardDataResponse) GetResult() isUpdateCardDataResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateCardDataResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*UpdateCardDataResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *UpdateCardDataResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UpdateCardDataResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateCardDataResponse_Result interface {
	isUpdateCardDataResponse_Result()
}

type UpdateCardDataResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type UpdateCardDataResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UpdateCardDataResponse_Card) isUpdateCardDataResponse_Result() {}

func (*UpdateCardDataResponse_Error) isUpdateCardDataResponse_Result() {}

type UpdateCardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardStatusRequest) Reset() {
	*x = UpdateCardStatusRequest{}
	mi := &file_proto_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardStatusRequest) ProtoMessage() {}

func (x *UpdateCardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCardStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCardStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCardStatusResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateCardStatusResponse_Card
	//	*UpdateCardStatusResponse_Error
	Result        isUpdateCardStatusResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardStatusResponse) Reset() {
	*x = UpdateCardStatusResponse{}
	mi := &file_proto_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardStatusResponse) ProtoMessage() {}

func (x *UpdateCardStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCardStatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateCardStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCardStatusResponse) GetResult() isUpdateCardStatusResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateCardStatusResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*UpdateCardStatusResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *UpdateCardStatusResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*UpdateCardStatusResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateCardStatusResponse_Result interface {
	isUpdateCardStatusResponse_Result()
}

type UpdateCardStatusResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type UpdateCardStatusResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*UpdateCardStatusResponse_Card) isUpdateCardStatusResponse_Result() {}

func (*UpdateCardStatusResponse_Error) isUpdateCardStatusResponse_Result() {}

type DeleteCardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardDataRequest) Reset() {
	*x = DeleteCardDataRequest{}
	mi := &file_proto_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardDataRequest) ProtoMessage() {}

func (x *DeleteCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCardDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCardDataResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*DeleteCardDataResponse_Card
	//	*DeleteCardDataResponse_Error
	Result        isDeleteCardDataResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardDataResponse) Reset() {
	*x = DeleteCardDataResponse{}
	mi := &file_proto_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardDataResponse) ProtoMessage() {}

func (x *DeleteCardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCardDataResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteCardDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteCardDataResponse) GetResult() isDeleteCardDataResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeleteCardDataResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*DeleteCardDataResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *DeleteCardDataResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*DeleteCardDataResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDeleteCardDataResponse_Result interface {
	isDeleteCardDataResponse_Result()
}

type DeleteCardDataResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type DeleteCardDataResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*DeleteCardDataResponse_Card) isDeleteCardDataResponse_Result() {}

func (*DeleteCardDataResponse_Error) isDeleteCardDataResponse_Result() {}

type GetCardByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardByUserIDRequest) Reset() {
	*x = GetCardByUserIDRequest{}
	mi := &file_proto_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardByUserIDRequest) ProtoMessage() {}

func (x *GetCardByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetCardByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{12}
}

func (x *GetCardByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCardByUserIDResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetCardByUserIDResponse_Card
	//	*GetCardByUserIDResponse_Error
	Result        isGetCardByUserIDResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardByUserIDResponse) Reset() {
	*x = GetCardByUserIDResponse{}
	mi := &file_proto_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardByUserIDResponse) ProtoMessage() {}

func (x *GetCardByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetCardByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{13}
}

func (x *GetCardByUserIDResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetCardByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCardByUserIDResponse) GetResult() isGetCardByUserIDResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetCardByUserIDResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*GetCardByUserIDResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *GetCardByUserIDResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*GetCardByUserIDResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetCardByUserIDResponse_Result interface {
	isGetCardByUserIDResponse_Result()
}

type GetCardByUserIDResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type GetCardByUserIDResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*GetCardByUserIDResponse_Card) isGetCardByUserIDResponse_Result() {}

func (*GetCardByUserIDResponse_Error) isGetCardByUserIDResponse_Result() {}

type SearchCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardRequest) Reset() {
	*x = SearchCardRequest{}
	mi := &file_proto_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardRequest) ProtoMessage() {}

func (x *SearchCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardRequest.ProtoReflect.Descriptor instead.
func (*SearchCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{14}
}

func (x *SearchCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type SearchCardResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*SearchCardResponse_Cards
	//	*SearchCardResponse_Error
	Result        isSearchCardResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardResponse) Reset() {
	*x = SearchCardResponse{}
	mi := &file_proto_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardResponse) ProtoMessage() {}

func (x *SearchCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardResponse.ProtoReflect.Descriptor instead.
func (*SearchCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{15}
}

func (x *SearchCardResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SearchCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchCardResponse) GetResult() isSearchCardResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SearchCardResponse) GetCards() *Card {
	if x != nil {
		if x, ok := x.Result.(*SearchCardResponse_Cards); ok {
			return x.Cards
		}
	}
	return nil
}

func (x *SearchCardResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*SearchCardResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSearchCardResponse_Result interface {
	isSearchCardResponse_Result()
}

type SearchCardResponse_Cards struct {
	Cards *Card `protobuf:"bytes,3,opt,name=cards,proto3,oneof"`
}

type SearchCardResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SearchCardResponse_Cards) isSearchCardResponse_Result() {}

func (*SearchCardResponse_Error) isSearchCardResponse_Result() {}

type FindCardByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCardByStatusRequest) Reset() {
	*x = FindCardByStatusRequest{}
	mi := &file_proto_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCardByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCardByStatusRequest) ProtoMessage() {}

func (x *FindCardByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCardByStatusRequest.ProtoReflect.Descriptor instead.
func (*FindCardByStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{16}
}

func (x *FindCardByStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindCardByStatusResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*FindCardByStatusResponse_Cards
	//	*FindCardByStatusResponse_Error
	Result        isFindCardByStatusResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCardByStatusResponse) Reset() {
	*x = FindCardByStatusResponse{}
	mi := &file_proto_card_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCardByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCardByStatusResponse) ProtoMessage() {}

func (x *FindCardByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCardByStatusResponse.ProtoReflect.Descriptor instead.
func (*FindCardByStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{17}
}

func (x *FindCardByStatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FindCardByStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindCardByStatusResponse) GetResult() isFindCardByStatusResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FindCardByStatusResponse) GetCards() *Card {
	if x != nil {
		if x, ok := x.Result.(*FindCardByStatusResponse_Cards); ok {
			return x.Cards
		}
	}
	return nil
}

func (x *FindCardByStatusResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*FindCardByStatusResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isFindCardByStatusResponse_Result interface {
	isFindCardByStatusResponse_Result()
}

type FindCardByStatusResponse_Cards struct {
	Cards *Card `protobuf:"bytes,3,opt,name=cards,proto3,oneof"`
}

type FindCardByStatusResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*FindCardByStatusResponse_Cards) isFindCardByStatusResponse_Result() {}

func (*FindCardByStatusResponse_Error) isFindCardByStatusResponse_Result() {}

type StripePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StripePaymentRequest) Reset() {
	*x = StripePaymentRequest{}
	mi := &file_proto_card_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripePaymentRequest) ProtoMessage() {}

func (x *StripePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripePaymentRequest.ProtoReflect.Descriptor instead.
func (*StripePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{18}
}

func (x *StripePaymentRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *StripePaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *StripePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type StripePaymentResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*StripePaymentResponse_Card
	//	*StripePaymentResponse_Error
	Result        isStripePaymentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StripePaymentResponse) Reset() {
	*x = StripePaymentResponse{}
	mi := &file_proto_card_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripePaymentResponse) ProtoMessage() {}

func (x *StripePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripePaymentResponse.ProtoReflect.Descriptor instead.
func (*StripePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{19}
}

func (x *StripePaymentResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *StripePaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StripePaymentResponse) GetResult() isStripePaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StripePaymentResponse) GetCard() *Card {
	if x != nil {
		if x, ok := x.Result.(*StripePaymentResponse_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *StripePaymentResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Result.(*StripePaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStripePaymentResponse_Result interface {
	isStripePaymentResponse_Result()
}

type StripePaymentResponse_Card struct {
	Card *Card `protobuf:"bytes,3,opt,name=card,proto3,oneof"`
}

type StripePaymentResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*StripePaymentResponse_Card) isStripePaymentResponse_Result() {}

func (*StripePaymentResponse_Error) isStripePaymentResponse_Result() {}

var File_proto_card_proto protoreflect.FileDescriptor

const file_proto_card_proto_rawDesc = "" +
	"\n" +
	"\x10proto/card.proto\x12\x05cards\"\xb6\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"cardNumber\x18\x03 \x01(\tR\n" +
	"cardNumber\x12&\n" +
	"\x0ecardHolderName\x18\x04 \x01(\tR\x0ecardHolderName\x12&\n" +
	"\x0eexpirationDate\x18\x05 \x01(\tR\x0eexpirationDate\x12\x10\n" +
	"\x03cvv\x18\x06 \x01(\tR\x03cvv\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\bcardType\x18\b \x01(\tR\bcardType\x12\x18\n" +
	"\abalance\x18\t \x01(\tR\abalance\x12\x1a\n" +
	"\bcreateAt\x18\n" +
	" \x01(\tR\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\v \x01(\tR\bupdateAt\"t\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"$\n" +
	"\x12GetCardByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa9\x01\n" +
	"\x13GetCardByIDResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\xfe\x01\n" +
	"\x14CreateNewCardRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"cardNumber\x18\x02 \x01(\tR\n" +
	"cardNumber\x12&\n" +
	"\x0ecardHolderName\x18\x03 \x01(\tR\x0ecardHolderName\x12&\n" +
	"\x0eexpirationDate\x18\x04 \x01(\tR\x0eexpirationDate\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bcardType\x18\a \x01(\tR\bcardType\x12\x18\n" +
	"\abalance\x18\b \x01(\tR\abalance\"\xab\x01\n" +
	"\x15CreateNewCardResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"\xf7\x01\n" +
	"\x15UpdateCardDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"cardNumber\x18\x02 \x01(\tR\n" +
	"cardNumber\x12&\n" +
	"\x0ecardHolderName\x18\x03 \x01(\tR\x0ecardHolderName\x12&\n" +
	"\x0eexpirationDate\x18\x04 \x01(\tR\x0eexpirationDate\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bcardType\x18\a \x01(\tR\bcardType\x12\x18\n" +
	"\abalance\x18\b \x01(\tR\abalance\"\xac\x01\n" +
	"\x16UpdateCardDataResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"A\n" +
	"\x17UpdateCardStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xae\x01\n" +
	"\x18UpdateCardStatusResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"'\n" +
	"\x15DeleteCardDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xac\x01\n" +
	"\x16DeleteCardDataResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"0\n" +
	"\x16GetCardByUserIDRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xad\x01\n" +
	"\x17GetCardByUserIDResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"3\n" +
	"\x11SearchCardRequest\x12\x1e\n" +
	"\n" +
	"cardNumber\x18\x01 \x01(\tR\n" +
	"cardNumber\"\xaa\x01\n" +
	"\x12SearchCardResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x05cards\x18\x03 \x01(\v2\v.cards.CardH\x00R\x05cards\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"1\n" +
	"\x17FindCardByStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb0\x01\n" +
	"\x18FindCardByStatusResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x05cards\x18\x03 \x01(\v2\v.cards.CardH\x00R\x05cards\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result\"b\n" +
	"\x14StripePaymentRequest\x12\x16\n" +
	"\x06cardId\x18\x01 \x01(\tR\x06cardId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xab\x01\n" +
	"\x15StripePaymentResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04card\x18\x03 \x01(\v2\v.cards.CardH\x00R\x04card\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.cards.ErrorDetailsH\x00R\x05errorB\b\n" +
	"\x06result2\xc8\x05\n" +
	"\vCardService\x12D\n" +
	"\vGetCardByID\x12\x19.cards.GetCardByIDRequest\x1a\x1a.cards.GetCardByIDResponse\x12J\n" +
	"\rCreateNewCard\x12\x1b.cards.CreateNewCardRequest\x1a\x1c.cards.CreateNewCardResponse\x12M\n" +
	"\x0eUpdateCardData\x12\x1c.cards.UpdateCardDataRequest\x1a\x1d.cards.UpdateCardDataResponse\x12M\n" +
	"\x0eDeleteCardData\x12\x1c.cards.DeleteCardDataRequest\x1a\x1d.cards.DeleteCardDataResponse\x12S\n" +
	"\x10UpdateCardStatus\x12\x1e.cards.UpdateCardStatusRequest\x1a\x1f.cards.UpdateCardStatusResponse\x12P\n" +
	"\x0fGetCardByUserID\x12\x1d.cards.GetCardByUserIDRequest\x1a\x1e.cards.GetCardByUserIDResponse\x12A\n" +
	"\n" +
	"SearchCard\x12\x18.cards.SearchCardRequest\x1a\x19.cards.SearchCardResponse\x12S\n" +
	"\x10FindCardByStatus\x12\x1e.cards.FindCardByStatusRequest\x1a\x1f.cards.FindCardByStatusResponse\x12J\n" +
	"\rStripePayment\x12\x1b.cards.StripePaymentRequest\x1a\x1c.cards.StripePaymentResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_card_proto_rawDescOnce sync.Once
	file_proto_card_proto_rawDescData []byte
)

func file_proto_card_proto_rawDescGZIP() []byte {
	file_proto_card_proto_rawDescOnce.Do(func() {
		file_proto_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_proto_rawDesc), len(file_proto_card_proto_rawDesc)))
	})
	return file_proto_card_proto_rawDescData
}

var file_proto_card_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_card_proto_goTypes = []any{
	(*Card)(nil),                     // 0: cards.Card
	(*ErrorDetails)(nil),             // 1: cards.ErrorDetails
	(*GetCardByIDRequest)(nil),       // 2: cards.GetCardByIDRequest
	(*GetCardByIDResponse)(nil),      // 3: cards.GetCardByIDResponse
	(*CreateNewCardRequest)(nil),     // 4: cards.CreateNewCardRequest
	(*CreateNewCardResponse)(nil),    // 5: cards.CreateNewCardResponse
	(*UpdateCardDataRequest)(nil),    // 6: cards.UpdateCardDataRequest
	(*UpdateCardDataResponse)(nil),   // 7: cards.UpdateCardDataResponse
	(*UpdateCardStatusRequest)(nil),  // 8: cards.UpdateCardStatusRequest
	(*UpdateCardStatusResponse)(nil), // 9: cards.UpdateCardStatusResponse
	(*DeleteCardDataRequest)(nil),    // 10: cards.DeleteCardDataRequest
	(*DeleteCardDataResponse)(nil),   // 11: cards.DeleteCardDataResponse
	(*GetCardByUserIDRequest)(nil),   // 12: cards.GetCardByUserIDRequest
	(*GetCardByUserIDResponse)(nil),  // 13: cards.GetCardByUserIDResponse
	(*SearchCardRequest)(nil),        // 14: cards.SearchCardRequest
	(*SearchCardResponse)(nil),       // 15: cards.SearchCardResponse
	(*FindCardByStatusRequest)(nil),  // 16: cards.FindCardByStatusRequest
	(*FindCardByStatusResponse)(nil), // 17: cards.FindCardByStatusResponse
	(*StripePaymentRequest)(nil),     // 18: cards.StripePaymentRequest
	(*StripePaymentResponse)(nil),    // 19: cards.StripePaymentResponse
}
var file_proto_card_proto_depIdxs = []int32{
	0,  // 0: cards.GetCardByIDResponse.card:type_name -> cards.Card
	1,  // 1: cards.GetCardByIDResponse.error:type_name -> cards.ErrorDetails
	0,  // 2: cards.CreateNewCardResponse.card:type_name -> cards.Card
	1,  // 3: cards.CreateNewCardResponse.error:type_name -> cards.ErrorDetails
	0,  // 4: cards.UpdateCardDataResponse.card:type_name -> cards.Card
	1,  // 5: cards.UpdateCardDataResponse.error:type_name -> cards.ErrorDetails
	0,  // 6: cards.UpdateCardStatusResponse.card:type_name -> cards.Card
	1,  // 7: cards.UpdateCardStatusResponse.error:type_name -> cards.ErrorDetails
	0,  // 8: cards.DeleteCardDataResponse.card:type_name -> cards.Card
	1,  // 9: cards.DeleteCardDataResponse.error:type_name -> cards.ErrorDetails
	0,  // 10: cards.GetCardByUserIDResponse.card:type_name -> cards.Card
	1,  // 11: cards.GetCardByUserIDResponse.error:type_name -> cards.ErrorDetails
	0,  // 12: cards.SearchCardResponse.cards:type_name -> cards.Card
	1,  // 13: cards.SearchCardResponse.error:type_name -> cards.ErrorDetails
	0,  // 14: cards.FindCardByStatusResponse.cards:type_name -> cards.Card
	1,  // 15: cards.FindCardByStatusResponse.error:type_name -> cards.ErrorDetails
	0,  // 16: cards.StripePaymentResponse.card:type_name -> cards.Card
	1,  // 17: cards.StripePaymentResponse.error:type_name -> cards.ErrorDetails
	2,  // 18: cards.CardService.GetCardByID:input_type -> cards.GetCardByIDRequest
	4,  // 19: cards.CardService.CreateNewCard:input_type -> cards.CreateNewCardRequest
	6,  // 20: cards.CardService.UpdateCardData:input_type -> cards.UpdateCardDataRequest
	10, // 21: cards.CardService.DeleteCardData:input_type -> cards.DeleteCardDataRequest
	8,  // 22: cards.CardService.UpdateCardStatus:input_type -> cards.UpdateCardStatusRequest
	12, // 23: cards.CardService.GetCardByUserID:input_type -> cards.GetCardByUserIDRequest
	14, // 24: cards.CardService.SearchCard:input_type -> cards.SearchCardRequest
	16, // 25: cards.CardService.FindCardByStatus:input_type -> cards.FindCardByStatusRequest
	18, // 26: cards.CardService.StripePayment:input_type -> cards.StripePaymentRequest
	3,  // 27: cards.CardService.GetCardByID:output_type -> cards.GetCardByIDResponse
	5,  // 28: cards.CardService.CreateNewCard:output_type -> cards.CreateNewCardResponse
	7,  // 29: cards.CardService.UpdateCardData:output_type -> cards.UpdateCardDataResponse
	11, // 30: cards.CardService.DeleteCardData:output_type -> cards.DeleteCardDataResponse
	9,  // 31: cards.CardService.UpdateCardStatus:output_type -> cards.UpdateCardStatusResponse
	13, // 32: cards.CardService.GetCardByUserID:output_type -> cards.GetCardByUserIDResponse
	15, // 33: cards.CardService.SearchCard:output_type -> cards.SearchCardResponse
	17, // 34: cards.CardService.FindCardByStatus:output_type -> cards.FindCardByStatusResponse
	19, // 35: cards.CardService.StripePayment:output_type -> cards.StripePaymentResponse
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_card_proto_init() }
func file_proto_card_proto_init() {
	if File_proto_card_proto != nil {
		return
	}
	file_proto_card_proto_msgTypes[3].OneofWrappers = []any{
		(*GetCardByIDResponse_Card)(nil),
		(*GetCardByIDResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[5].OneofWrappers = []any{
		(*CreateNewCardResponse_Card)(nil),
		(*CreateNewCardResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[7].OneofWrappers = []any{
		(*UpdateCardDataResponse_Card)(nil),
		(*UpdateCardDataResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[9].OneofWrappers = []any{
		(*UpdateCardStatusResponse_Card)(nil),
		(*UpdateCardStatusResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[11].OneofWrappers = []any{
		(*DeleteCardDataResponse_Card)(nil),
		(*DeleteCardDataResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[13].OneofWrappers = []any{
		(*GetCardByUserIDResponse_Card)(nil),
		(*GetCardByUserIDResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[15].OneofWrappers = []any{
		(*SearchCardResponse_Cards)(nil),
		(*SearchCardResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[17].OneofWrappers = []any{
		(*FindCardByStatusResponse_Cards)(nil),
		(*FindCardByStatusResponse_Error)(nil),
	}
	file_proto_card_proto_msgTypes[19].OneofWrappers = []any{
		(*StripePaymentResponse_Card)(nil),
		(*StripePaymentResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_proto_rawDesc), len(file_proto_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_proto_goTypes,
		DependencyIndexes: file_proto_card_proto_depIdxs,
		MessageInfos:      file_proto_card_proto_msgTypes,
	}.Build()
	File_proto_card_proto = out.File
	file_proto_card_proto_goTypes = nil
	file_proto_card_proto_depIdxs = nil
}
